<?php
!function_exists('readover') && exit('Forbidden');
$lang['logtype'] = array(
	'creditlog'	=> array(
		'main'				=> '论坛相关',
		'main_buygroup'		=> '用户组购买',
		'main_showsign'		=> '签名展示',
		'main_forumsell'	=> '版块权限购买',
		'main_changereduce'	=> '积分转换(-)',
		'main_changeadd'	=> '积分转换(+)',
		'main_virefrom'		=> '积分转帐(-)',
		'main_vireto'		=> '积分转帐(+)',
		'main_olpay'		=> '在线充值',

		'reg'				=> '注册',
		'reg_register'		=> '用户注册',

		'topic'				=> '帖子相关',
		'topic_Post'		=> '发帖奖励',
		'topic_Reply'		=> '回帖奖励',
		'topic_upload'		=> '附件上传',
		'topic_download'	=> '附件下载',
		'topic_Digest'		=> '设置精华',
		'topic_Delete'		=> '删除主题',
		'topic_Deleterp'	=> '删除回复',
		'topic_Undigest'	=> '取消精华',
		'topic_buy'			=> '帖子购买',
		'topic_sell'		=> '帖子出售',
		'topic_attbuy'		=> '附件购买',
		'topic_attsell'		=> '附件出售',

		'credit'			=> '评分',
		'credit_showping'	=> '帖子评分',
		'credit_delping'	=> '取消评分',
		'reward'			=> '悬赏',
		'reward_new'		=> '发布悬赏',
		'reward_modify'		=> '追加悬赏',
		'reward_answer'		=> '最佳答案奖励',
		'reward_active'		=> '热心助人奖励',
		'reward_return'		=> '悬赏返分',

		'hack'				=> '插件',
		'hack_banksave1'	=> '活期存款',
		'hack_banksave2'	=> '定期存款',
		'hack_bankdraw1'	=> '活期取款',
		'hack_bankdraw2'	=> '定期取款',
		'hack_cytransfer'	=> '转让群',
		'hack_cycreate'		=> '创建群',
		'hack_cyjoin'		=> '加入群',
		'hack_cydonate'		=> '群充值',
		'hack_cyvire'		=> '群转帐',
		'hack_cyalbum'		=> '创建群相册',
		'hack_dbpost'		=> '发表辩论',
		'hack_dbreply'		=> '参与辩论',
		'hack_dbdelt'		=> '删除辩论',
		'hack_toolubuy'		=> '购买用户道具',
		'hack_toolbuy'		=> '购买系统道具',
		'hack_toolsell'		=> '出售道具',
		'hack_teampay'		=> '版主考勤',
		'hack_invcodebuy'	=> '邀请码购买',
		/* phpwind.net */
		'hack_creditget'	=> '积分领取',
		'hack_creditaward'	=> '积分兑换',

		'share_Delete'		=> '删除分享',
		'share_Post'		=> '分享奖励',
		'diary_Delete'		=> '删除日志',
		'diary_Post'		=> '日志奖励',
		'groups_Uploadphoto'=> '照片奖励',
		'groups_Deletephoto'=> '删除照片',
		'groups_Createalbum'=> '创建相册',
		'groups_Postarticle'=> '文章奖励',
		'groups_Deletearticle'=> '删除文章',
		'groups_Joingroup'  => '加入群组',
		'groups_Creategroup'=> '创建群组',
		'photos_Deletephoto'=> '删除照片',
		'photos_Uploadphoto'=> '照片奖励',
		'photos_Createalbum'=> '创建相册',
		'weibo_Post'        => '新鲜事奖励',
		'weibo_Delete'      => '删除新鲜事',

		'other'				=> '其它',
		'other_present'		=> '节日送礼',
		'other_finishjob'	=> '任务奖励',
		'other_propaganda' 	=> '宣传奖励',
		'other_finishpunch' => '打卡奖励',
	),

	'bk_save'			=> '存款',
	'bk_draw'			=> '取款',
	'bk_vire'			=> '转帐',

	'topped'			=> '置顶',
	'digest'			=> '精华',
	'highlight'			=> '加亮',
	'push'				=> '提前',
	'pushto'			=> '推送',
	'down'				=> '压帖',
	'locked'			=> '锁定',
	'delrp'				=> '删回复',
	'deltpc'			=> '删主题',
	'delete'			=> '删除',
	'move'				=> '移动',
	'copy'				=> '复制',
	'edit'				=> '编辑',
	'shield'			=> '屏蔽',
	'unite'				=> '合并',
	'remind'			=> '提醒',
	'recycle'			=> '回收站',
	'banuser'			=> '禁言',
	'banuserip'			=> '禁止IP',
	'signature'			=> '禁止签名',

	'credit'			=> '评分',
	'deluser'			=> '用户',

	'cy_donate'			=> '捐献',
	'cy_join'			=> '加群',
	'cy_vire'			=> '转帐',

);
?>