<?php
!function_exists('readover') && exit('Forbidden');

$lang['bbscode'] = array (

'full_screen'			=> '全屏播放',
'bbcode_hide1'			=> '本部分设定了隐藏,您已回复过了,以下是隐藏的内容',
'bbcode_hide2'			=> '本部分设定了隐藏,您是楼主,以下是隐藏的内容',
'bbcode_hide3'			=> '本部分设定了隐藏,您有查看隐藏帖子的权限,以下是隐藏的内容',
'bbcode_hide4'			=> '本部分设定了隐藏,您是管理员或版主,以下是隐藏的内容',
'bbcode_hide'			=> '本部分内容设定了隐藏,需要回复后才能看到',
'bbcode_encode1'		=> '本部分内容设定了加密,查看此帖需要{$L[name]}:{$L[value]}',
'bbcode_encode2'		=> '该帖是加密帖,需要{$L[value]}{$L[name]}以上的积分才能浏览以下内容:',
'bbcode_encode3'		=> '对不起!您没有登录,请先<a href="login.php"><font color="red">登录论坛</font></a>.',

'bbcode_sell_info'		=> '此帖售价 $L[value] $L[name],已有 $L[count] 人购买',
'bbcode_sell_infonotice'=> '<span class="mr10">此段为出售的内容，购买后显示</span><!--a href="$L[buy]" onclick="return ajaxurl(this);">[购买]</a-->',

'bbcode_sell_buy'		=> '购买人名单',
'bbcode_sell_record_buy'=> '<a href="$L[record]" onclick="return ajaxurl(this);" title="查看记录" class="mr10"><font color="">[记录]</font></a> <a href="$L[buy]" onclick="return ajaxurl(this);" title="购买" class="mr10"><font color="">[购买]</font></a>',
'bbcode_sell_submit'	=> '愿意购买,我买,我付钱',
'bbcode_sell_notice'	=> '购买后，将显示帖子中所有出售内容。<br>若发现会员采用欺骗的方法获取财富,请立刻举报,我们会对会员处以2-N倍的罚金,严重者封掉ID!',
'seller'				=> '<b>卖家：</b>',
'subject'				=> '<b>商品名称：</b>',
'body'					=> '<b>商品描述：</b>',
'price'					=> '<b>商品价格：</b>',
'postage'				=> '<b>邮费信息：</b>',
'postage_seller'		=> '<b>邮费信息：</b>卖家承担邮费',
'contact'				=> '<b>联系方式：</b>',
'demo'					=> '<b>演示地址：</b>',
'ordinary_fee'			=> '平邮：',
'express_fee'			=> '快递：',

'size'					=> '<b>软件大小：</b>',
'language'				=> '<b>软件语言：</b>',
'type'					=> '<b>软件类别：</b>',
'os'					=> '<b>运行环境：</b>',
'date'					=> '<b>更新时间：</b>',
'author'				=> '<b>软件添加：</b>',
'level'					=> '<b>软件评级：</b>',
'publish'				=> '<b>开 发 商：</b>',
'preview'				=> '<b>界面预览：</b>',
'hits'					=> '<b>下载次数：</b>',
'descrip'				=> '<b>软件简介：</b>',
'link'					=> '<b>下载地址：</b>',
'shield_title'			=> '该帖已被屏蔽',
'shield_del_title'		=> '该主题已被删除!',
'shield_article'		=> '该主题已被管理员屏蔽!',
'shield_del_article'	=> '该主题已被管理员删除!',
'post_unchecked'		=> '该帖还未通过检查',
'post_deleted'          => '该帖已被删除',
'ban_article'			=> '用户被禁言,该主题自动屏蔽!',
'rewarding'				=> '此帖悬赏中(剩余时间:',
'read_topped'			=> '执行 <span class="s2">帖内置顶</span> 操作',
'read_deltopped'		=> '执行  <span class="s2">取消置顶</span> 操作',
'read_topped_tag'		=> '帖内置顶',
'reward_bestanswer'		=> '最佳答案',
'reward_help'			=> '热心助人',
'reward_hlp'			=> '热心助人剩余点数',
'reward_cancle'			=> '[结束悬赏]',
'reward_toadmin'		=> '[联系版主]',
'reward_finished'		=> '此帖悬赏结束',
'reward_author'			=> '最佳答案获得者',
'reward_best_get'		=> '最佳答案奖励',
'reward_help_get'		=> '热心助人奖励',
'reward_manager'		=> '管理操作',
'reward_title'			=> '如果没有得到合适的答案,可以点此给版主发短消息.经由版主鉴定情况属实,可以返回最佳答案积分!',
'reward_msgtoadmin'		=> '是否联系版主,由版主来处理?',
'reward_endinfo_2'		=> '本次悬赏被取消',
'reward_endinfo_3'		=> '本次悬赏被强行结案',
'post_reply'			=> '楼主留言：',
'player_rm'				=> '点击播放多媒体',
'player_wmv'			=> '点击播放多媒体',
'player_flash'			=> '点击播放flash',
'hour'					=> '小时',
'minute'				=> '分钟',
'timeover'				=> '已结束',
'copycode'				=> '复制代码',
'qoute'					=> '引用',
);
?>