<?php
!function_exists('readover') && exit('Forbidden');

$lang['refreshto'] = array(
	'operate_success'		=> '操作完成',
	'have_login'			=> '您已经顺利登录{$GLOBALS[showmsginfo]}',
	'login_out'				=> '状态：您已经顺利退出网站{$GLOBALS[showmsginfo]}',
	'after_delete'			=> '<a href=thread.php?fid={$GLOBALS[fid]}>[ 删除成功点击进入主题列表 ]</a>',
	'enter_thread'			=> '<a href=thread.php?fid={$GLOBALS[fid]}>[ 发帖完毕点击进入主题列表 ]</a>',
	'enter_words'			=> '你发布的内容包含敏感词“<font color=\'red\'>{$GLOBALS[banword]}</font>”，相关内容将被替换!',
	'reg_success'			=> '恭喜您,完成注册现在可以开始使用您的会员权利了',
	'mail_success'			=> '邮件发送完成',
	'enter_c_thread'		=> '<a href=c_thread.php?fid={$GLOBALS[fid]}>[ 发帖完毕点击进入主题列表 ]</a>',
	'post_word_check'		=> '你发布的内容包含敏感词“<font color=\'red\'>{$GLOBALS[banword]}</font>”，需要管理员审核后才能显示!',
	'post_check'			=> '本版块开启了发帖审核功能,需要管理员审核后才能显示!',
	'success_check'			=> '<a href=thread.php?fid={$GLOBALS[fid]}>[ 回复完毕,本版块开启了发帖审核功能,需要管理员审核后才能显示!]</a>',
	'post_link_check'		=> '内容中链接个数过多，需管理员审核通过后才能显示!',
	'masigle_ban_success'	=> '完成禁言,将自动跳转至会员资料页面',
	'masingle_bansignature_ban'	  => '已经成功禁止{$GLOBALS[readdb][username]}的帖子签名显示',			
	'masingle_bansignature_free'  => '已经成功解除{$GLOBALS[readdb][username]}的帖子签名屏蔽',	
	'masingle_banip_ban'		=> 'IP:{$GLOBALS[readdb][userip]} 已被禁止',
	'masingle_banip_free'		=> 'IP:{$GLOBALS[readdb][userip]} 已经恢复',	
	'update_cache'			=> '正在更新榜单排行缓存,请耐心等待...',
	'colony_regsuccess'		=> '{$GLOBALS[cn_name]}创建成功，进入{$GLOBALS[cn_name]}基本资料设置',
	'colony_cardsuccess'	=> '{$GLOBALS[cn_name]}名片修改成功。',
	'colony_postsuccess'	=> '发布成功。',
	'colony_editsuccess'	=> '编辑成功。',
	'colony_delsuccess'		=> '删除成功。',
	'colony_quitsuccess'	=> '退出成功。',
	'colony_setsuccess'		=> '{$GLOBALS[cn_name]}修改成功。',
	'colony_topsuccess'     => '帖子置顶成功。',
	'showsign_success'		=> '签名展示设置成功。',
	'bank_savesuccess'		=> '完成存款!',
	'bank_drawsuccess'		=> '完成取款!',
	'bank_viresuccess'		=> '完成转帐!',
	'bank_creditsuccess'	=> '完成积分转换!',
	'blog_enterhomepage'	=> '进入 {$GLOBALS[username]} 的个人主页',
	'friend_update_success'	=> '好友列表更新成功。',
	'friend_setting_success'=> '好友设置修改完成。',
	'friend_accept_success'	=> '您接受了好友请求',
	'friend_accept_add'		=> '你接受了请求并申请加对方为好友',
	'friend_refuse_success'	=> '您拒绝了好友请求',
	'friend_add_check'		=> '请求添加为好友，正在等待好友验证。',
	'friend_edit_descrip'	=> '好友描述编辑完成。',
	'post_limit_sell'		=> '您不能发起出售帖，请联系管理员',
	'post_limit_hide'		=> '您不能发起隐藏帖，请联系管理员',
	'post_limit_encode'		=> '您不能发起加密帖，请联系管理员',

	'complete_list'			=> '该订单已完成支付。',
	'bakup_step'			=> '正在备份数据库表 {$GLOBALS[t_name]}: 共 {$GLOBALS[rows]} 条记录，已经备份至 {$GLOBALS[c_n]}  条记录<br><br>已生成 {$GLOBALS[f_num]} 个备份文件，程序将自动备份余下部分',
	'bakup_out'				=> '已全部备份,备份文件保存在data目录下，备份文件为<br>{$GLOBALS[bakfile]}',
	'backup_data'           => '论坛进入自动数据备份中，您将无法访问本论坛',
	'group_buy_success'     => '特殊组购买成功!!',

	'debate_post_success'	=> '辩论主题发表成功，现转入辩论主题页面！',
	'debate_post_check'		=> '辩论主题发表成功，请等待管理员的审核！',
	'debate_edit_success'	=> '辩论主题编辑成功!',
	'debate_del_success'	=> '辩论主题删除成功！',
	'debate_reply_success'	=> '观点发表成功！',
	'msg_unread'			=> '标记未读成功！',

	'delete_recycle'		=> '正在清理回收站数据，请稍侯...',

	'alipay_failure'		=> '安全验证参数校验失败，无法完成充值！',
	'alipay_ordersfailure'	=> '系统中没有您的支付订单，无法完成支付！',
	'alipay_orderssuccess'	=> '该订单已经支付成功！',
	'alipay_topayfailure'	=> '支付失败，无法完成操作！',

	'report_success'		=> '帖子报告成功!',
	'password_change_success'=> '完成密码修改',

	'email_invite_success'	=> '注册码购买成功，现在跳转至注册页，如果丢失注册码或有购买多个，请进入电子邮箱查收!',

	'upload_icon_success'	=> '头像修改成功!',
	'album_error'			=> '请先建立相册',
	'myapp_success'			=> '操作成功!',
	'add_friend_success'	=> '成功加该用户为好友',
	//7.5RC1 End
	'pcalipay_none'			=> '不存在此订单或者已完成支付！',
	'pcalipay_success'		=> '您好，您已经完成支付！',
	'del_success'			=> '完成删除操作',
	'toptopic_success'			=> '置顶操作成功！',
	'digest_success'			=> '精华操作成功！',
	'lock_success'				=> '锁定操作成功！',
	'pushtopic_success'			=> '提前操作成功！',
	'downtopic_success'			=> '压帖操作成功！',
	'deltopic_success'			=> '话题删除操作成功！',
	'highlight_success'			=> '加亮操作成功！',
	'type_success'				=> '主题分类操作成功！',

	//活动
	'act_authentication_success'=> '支付宝帐号绑定成功!',
	'act_authentication_fail'	=> '支付宝帐号绑定失败',
	'act_toalipay_failure'		=> '支付失败，请与发起人联系',
	'act_toalipay_payed'		=> "该费用已支付",
	'act_aa_detail_success'		=> "费用支付成功!",
	'act_refund_alipay_fail'	=> '系统出现异常，退款失败',
	'act_refund_fail'			=> '支付状态错误，退款失败',
	'act_refund_success'		=> '退款成功!',
	'act_refund_cost_error'		=> '退款金额大于最大可退数',
	'act_alipay_sign_failure'	=> '数字签名认证失败',
	'act_undefined_operate'		=> '非法操作',
	'mode_o_photos_private_3'   => '该相册已加密，请输入正确密码.',
	'operate_success_reload'	=> '操作成功!',
);
?>