<?php
!function_exists('readover') && exit('Forbidden');

$lang['msg'] = array (

'undefined_action'			=> '非法操作,请返回',
'no_jiechu'					=> '没有解除警告的权限,请返回',
'not_login'					=> '您还没有登录或注册，暂时不能使用此功能!',
'proclock'					=> '服务器繁忙，请稍侯重试!',
'visiter_login'				=> '只允许内部会员才能访问论坛!',
'refresh_limit'				=> '论坛设置:刷新不要快于 $GLOBALS[db_refreshtime] 秒',
'data_error'				=> '读取数据错误,原因：您要访问的链接无效,可能链接不完整,或数据已被删除!',
'user_not_exists'			=> '用户"{$GLOBALS[errorname]}"不存在',
'not_friend_message'		=> '用户{$GLOBALS[errorname]} 拒绝非好友的短信息',
'password_confirm'			=> '两次密码输入不一致，请重新输入',
'password_confirm_fail'		=> '密码验证失败',
'pwd_confirm_fail'			=> '原密码错误，修改密码、电子邮箱和安全问题需要输入原密码验证',
'password_change_success'	=> '完成密码修改',
'mail_success'				=> '我们已经发送您的密码到您的注册电子邮箱,请注意查收!',
'mail_failed'				=> '由于服务器邮件系统配置不正确,电子邮件发送失败',
'email_error'				=> '您输入的用户名和电子邮箱地址不符，请重新输入。',
'safecv_error'				=> '您输入的安全问题错误，请重新输入。',
'illegal_tid'				=> '帖子ID非法',
'ip_not_banned'				=> '错误操作，IP:{$GLOBALS[readdb][userip]} 未被禁止',
'masingle_no_ip'			=> '错误操作，没有指定IP地址',
'illegal_data'				=> '该帖子的主题内容已被删除',
'illegal_email'				=> '信箱没有填写或不符合检查标准，请确认没有错误',
'illegal_pay'				=> '交易帐号不符合检查标准，请确认没有错误',
'illegal_OICQ'				=> 'OICQ或ICQ号码不正确',
'illegal_username'			=> '此用户名包含不可接受字符或被管理员屏蔽,请选择其它用户名',
'illegal_password'			=> '密码包含不可接受字符,请使用英文和数字',
'illegal_customimg'			=> '非法自定义头像：必须以 http:// 开头，不可包含此字符\'|\'，必须在(1-{$GLOBALS[db_imgwidth]})*(1-{$GLOBALS[db_imgheight]})的大小范围里',
'illegal_loadimg'			=> '非法头像类型',
'style_same'				=> '风格未改动',
'style_error'				=> '风格不存在',
'style_bgimg_error'			=> '风格背景图地址错误',
'style_name_error'			=> '风格名称中不可包含字符\'_\'',
'style_color_error'			=> '风格颜色值格式错误',
'sign_limit'				=> '签名不可超过 {$GLOBALS[_G][signnum]} 字节',
'introduce_limit'			=> '自我简介不要超过 500 字节',
'username_limit'			=> '为了避免论坛用户名混乱,用户名中禁止使用大写字母,请使用小写字母',
'username_same'				=> '此用户名已经被注册,请选择其它用户名',
'ban_info1'					=> '你已经被管理员禁言, 禁言开始时间 {$GLOBALS[s_date]} ，结束时间 $GLOBALS[e_date] !',
'ban_info2'					=> '你已经被管理员禁言, 类型为永久禁言!',
'ban_info3'					=> '你已经被管理员强制禁言, 你的其他帐号同时也将被禁言!',
'del_error'					=> '没有选择要删除的选项',
'del_success'				=> '完成删除操作',
'credit_error'				=> '自定义积分ID错误',
'most_online'				=> '状态:发生错误,论坛在线会员数已经达到最大值{$GLOBALS[db_onlinelmt]},请稍后再来!',
'ip_ban'					=> '您的IP被禁止，不能访问论坛',
'check_error'				=> '认证码不正确或已过期',
'qcheck_error'				=> '请输入正确的验证问题答案',
'keyword_error'				=> '关键字必须被包含在主题中',
'pse_input_keyword'			=> '请输入关键字',
'hack_error'				=> '未安装此插件或此插件无前台显示!',

'bk_credit_change_error'	=> '你要转换的积分大于实际的积分',
'bk_credit_fillin_error'	=> '积分转换值填写不正确！必需为大于零的整数',
'bk_credit_type_error'		=> '不支持这种积分转换方式',
'bk_virement_error'			=> '自己无法给自己转帐！',
'bk_no_enough_deposit'		=> '您的存款不够支付转帐和手续费，无法实现转帐！',
'bk_virement_count_error'	=> '转帐数目填写不正确！必需填写大于等于{$GLOBALS[bk_virelimit]}的整数',
'bk_virement_close'			=> '现在不允许转帐',
'bk_draw_error'				=> '取款金额大于您的存款金额！',
'bk_draw_fillin_error'		=> '取款数目填写不正确！必需填写大于零的整数',
'bk_save_error'				=> '存款金额大于您拥有的金额！',
'bk_save_fillin_error'		=> '存款数据错误！必需输入大于零的整数',
'bk_time_limit'				=> '{$GLOBALS[bk_timelimit]}秒内不允许重新交易',
'bk_close'					=> '银行被管理员关闭',

'readvote_noright'			=> '对不起，您没有权限查看投票会员',

'upload_group_right'		=> '用户组权限：你所属的用户组没有上传附件的权限',
'upload_forum_right'		=> '对不起，本版块只有特定用户可以上传附件，请返回',
'upload_close'				=> '附件上传功能已关闭',
'upload_size_0'				=> '附件{$GLOBALS[atc_attachment_name]}的大小不能为0',
'upload_size_error'			=> '附件 {$GLOBALS[atc_attachment_name]} 超过指定大小'
								. '({$GLOBALS[oversize]})KB',
'upload_type_error'			=> '附件{$GLOBALS[atc_attachment_name]}的类型不符合准则',
'upload_num_error'			=> '您今天上传的附件已经达到指定个数({$GLOBALS[_G][allownum]} 个)',
'upload_error'				=> '上传附件失败，造成的原因可能有:附件目录不可写(777)、空间在安全模式下、空间大小已不足。',
'upload_content_error'		=> '附件$GLOBALS[atc_attachment_name]内容非法,系统已经将其自动删除!',

'reply_ifcheck'				=> '该帖未通过管理员验证，不可回复',
'reply_lockatc'				=> '该帖已被锁定，不可回复',
'reply_group_right'			=> '用户组权限：你所属的用户组没有发表回复的权限!',
'reply_forum_right'			=> '本版块只有特定用户组才能回复主题,请到其他版块回帖,以提高等级!',

'post_credit_enough'		=> '您的积分不足，本版发帖需扣除 {$GLOBALS[shortCredit]}<br />请<a href="faq.php">赚取足够积分</a>后再来本版发帖。',
'postnew_group_right'		=> '用户组权限：你所属的用户组没有发表主题的权限!',
'postnew_forum_right'		=> '本版块只有特定用户组才能发表主题,请到其他版块发帖,以提高等级!',
'postnew_group_vote'		=> '用户组权限：你所属的用户组没有发表投票的权限',
'postnew_group_active'		=> '用户组权限：你所属的用户组没有发起活动的权限',
'postnew_group_reward'		=> '用户组权限：你所属的用户组没有发起悬赏的权限',
'postnew_group_goods'		=> '用户组权限：你所属的用户组没有发起商品的权限',
'postnew_group_debate'		=> '用户组权限：你所属的用户组没有发起辩论的权限',
'post_price_limit'			=> '超过出售帖允许的积分大小',

'modify_noper'				=> '您无权限编辑别人的帖子',
'modify_locked'				=> '该帖已被锁定，不可编辑',
'modify_admin'				=> '您无权编辑管理员、总版主或论坛版主的帖子',
'modify_timelimit'			=> '拒绝用户编辑:您已超过编辑时间限制 {$GLOBALS[_G][edittime]} 分钟',
'modify_forumtimelimit'     => '拒绝用户编辑:您已超过版块编辑时间限制 {$GLOBALS[postedittime]} 分钟',
'vote_not_modify'			=> '该投票主题不允许修改投票结果!',
'modify_group_right'		=> '您所在的用户组,没有权限删除自己的帖子',
'modify_replied'			=> '主题已被回复,不能删除',
'modify_del_right'			=> '你没有权限直接删除其他会员的帖子',

'postfunc_noempty'			=> '投票选项不能为空。',
'postfunc_money_limit'		=> '出售价格错误,应在0-1000之间',
'postfunc_subject_limit'	=> '标题为空或标题太长(请控制在  <font color="red">{$GLOBALS[db_titlemax]}</font> 字节)',
'postfunc_content_limit'	=> '内容长度错误(请控制在  <font color="red">{$GLOBALS[db_postmin]}-{$GLOBALS[db_postmax]}</font> 字节)',
'postfunc_content_threadlimit'	=>	'内容长度错误(本版块控制为  <font color="red">{$GLOBALS[contentMinLength]}-{$GLOBALS[db_postmax]}</font> 字节)',
'postfunc_upgrade_error'	=> '无此提升方式',

'msg_refuse'				=> '您发送的消息被用户<b>{$GLOBALS[errorname]}</b>拒绝',

'forumpw_pwd_error'			=> '密码错误,请重新输入密码',
'forumpw_guest'				=> '游客无权登录加密版块',
'forumpw_needpwd'			=> '本版块为加密版块,需密码验证( 游客无权登录此版块)',
'forum_sell'				=> '本版块为出售版块，需要支付一定积分才能浏览，<a style="color:blue;" href="profile.php?action=forumsell&fid=$GLOBALS[fid]" target="_blank">立即购买!</a>',
'forumsell_error'			=> '该版没有开启版块出售功能!',
'forumsell_already'			=> '您已经购买了该版块的访问权限!',
'forumsell_date'			=> '请选择购买期限!',
'forumsell_price'			=> '您没有足够的<b>{$GLOBALS[creditname]}</b>购买该版块的访问权限!',

'forum_hidden'				=> '本版块为隐藏版块,您无权进入!',
'forum_jiami'				=> '对不起,本版块为认证版块,您没有权限查看此版块的内容!',
'forum_read_right'			=> '对不起,本版块只有特定会员才能浏览帖子!',
'forum_former'				=> '本版块为正规版块,只有注册会员才能进入!',
'forum_guestlimit'			=> '对不起，本版块只允许注册会员进入!',

'sort_group_right'			=> '用户组权限：你所属的用户组不能查看统计与排行',

'sendpwd_limit'				=> '<font color=red>发送失败</font>:请不要在 {$GLOBALS[_G][postpertime]} 秒内连续性的使用此功能.',

'sendeamil_subject_limit'	=> '邮件标题为空，请填写',
'sendeamil_content_limit'	=> '请填写邮件内容并在20字节之上',
'sendeamil_limit'			=> '<font color=red>发送失败</font>:不要连续发送邮件.请等候....',
'sendeamil_refused'			=> '用户<b>{$GLOBALS[userdb][username]}</b>不接受邮件',

'search_opensch'			=> '由于网站流量的原因, 站点开放搜索时间为 {$GLOBALS[db_schstart]}:00 点到 {$GLOBALS[db_schend]}:00 点 !',
'search_wait'				=> '搜索排队中，请在 $GLOBALS[db_schwait] 秒后进行搜索',
'no_condition'				=> '请输入搜索条件.',
'search_none'				=> '没有查找匹配的内容',
'search_forum_right'		=> '您无权搜索此版块帖子',
'search_group_right'		=> '用户组权限：你所属的用户组不能使用搜索功能',
'search_tpost'				=> '用户组权限：你所属的用户组不能搜索主题和内容',
'search_limit'				=> '对不起{$GLOBALS[_G][searchtime]}秒内只能进行一次搜索',
'search_word_limit'			=> '关键字长度不足2个字符，请重新输入',
'search_cate'				=> '不能搜索分类',
'illegal_keyword'			=> '关键字非法.',
'illegal_author'			=> '用户名非法.',

'reg_email_fail'			=> '帐号需要激活,激活邮件发送失败,请联系管理员!',
'reg_email_success'			=> '您的帐号需要激活,我们已经发送了一封邮件到您的电子邮箱，请查收!',
'reg_username_limit'		=> '注册名长度错误,请控制在 $GLOBALS[rg_regminname] - $GLOBALS[rg_regmaxname] 字节以内',
'reg_password_minlimit'		=> '密码格式错误：最小值不能少于$GLOBALS[rg_regminpwd]',
'reg_password_lowstring'	=> '密码格式错误：密码中必须存在小写字母',
'reg_password_upstring'		=> '密码格式错误：密码中必须存在大写字母',
'reg_password_num'			=> '密码格式错误：密码中必须存在数字',
'reg_password_specialstring'=> '密码格式错误：密码中必须存在特殊字符',
'reg_password_maxlimit'		=> '密码格式错误：最大值不能大于$GLOBALS[rg_regmaxpwd]',
'reg_nameuptopwd'			=> '密码格式错误：密码不允许与注册帐号相同',
'reg_repeat'				=> '您已经是注册成员,请不要重复注册!',
'reg_permit_notchecked'		=> '您未同意注册条款内容，注册失败',
'reg_limit'					=> '同一IP在{$GLOBALS[rg_config][rg_allowsameip]}小时内不能重复注册',
'reg_close'					=> '对不起,目前论坛禁止新用户注册,请返回!',
'reg_jihuo_fail'			=> '激活失败,错误原因:用户名不存在或验证参数有误!',
'reg_jihuo_success'			=> '完成激活密码,您的帐号已经激活,谢谢您的支持',
'reg_reason'				=> '请填写注册原因。',
'reg_email_have_same'		=> '您的电子邮箱地址有重复，请换个唯一的电子邮箱',
'reg_check'					=> '您还没通过管理员验证,需要通过管理员验证才能发言！',

'read_locked'				=> '此帖被管理员关闭，暂时不能浏览',
'read_check'				=> '这篇帖子还没通过管理员验证，暂时不能查看',
'read_group_right'			=> '用户组权限：你所属的用户组没有浏览帖子的权限',

'pro_custom_fail'			=> '要使用自定义头像功能前提 : 请先删除上传的头像',
'pro_loadimg_fail'			=> '您已经上传过头像，要重新上传头像请先删除原来上传的头像',
'pro_loadimg_close'			=> '头像上传功能已关闭',
'pro_loadimg_right'			=> '用户组权限：你所属的用户组没有上传附件的权限',
'pro_loadimg_limit'			=> '上传的头像超过指定大小$GLOBALS[db_imgsize] 字节',
'pro_loadimg_sizelimit'		=> '上传的头像必须在(0-$GLOBALS[db_imgwidth])*(0-$GLOBALS[db_imglen])的大小范围里',
'pro_loadimg_error'			=> '上传的头像错误：非法操作或头像无效!',
'pro_manager'				=> '创始人密码修改请到后台操作！',
'pro_emailcheck'			=> '系统开启了电子邮件验证系统，不允许更改电子邮件信息。',

'post_wordsfb'				=> '警告：您提交的内容中含有非法词语 \'<font color=red>$GLOBALS[banword]</font>\'！',
'title_wordsfb'				=> '标题中含有敏感词： \'<font color=red>{$GLOBALS[banword]}</font>\'，禁止发表，请返回修改',
'content_wordsfb'			=> '内容中含有敏感词： \'<font color=red>{$GLOBALS[banword]}</font>\'，禁止发表，请返回修改',
'tag_wordsfb'				=> '标签中含有敏感词：\'<font color=red>{$GLOBALS[banword]}</font>\'，禁止发表，请返回修改',
'sign_wordsfb'				=> '签名中含有敏感词： \'<font color=red>{$GLOBALS[banword]}</font>\'，禁止发表，请返回修改',
'diary_title_wordsfb'       => '标题中含有敏感词“<font color=red>{$GLOBALS[banword]}</font>”，禁止发表，请返回修改',
'diary_content_wordsfb'       => '内容中含有敏感词“<font color=red>{$GLOBALS[banword]}</font>”，禁止发表，请返回修改',

'post_gp_limit'				=> '用户组权限：你所属的用户组每日最多能发 {$GLOBALS[_G][postlimit]} 篇帖子.',
'post_limit'				=> '灌水预防机制已经打开，在{$GLOBALS[_G][postpertime]}秒内不能发帖',
'post_newrg_limit'			=> '新注册用户{$GLOBALS[db_postallowtime]}分钟内不能发帖！',
'post_check'				=> '您还没通过管理员验证,需要通过管理员验证才能发言！',
'post_verify'				=> '文章发表成功,本版块开启了发帖审核功能,请等待管理员审核!',
'post_openpost'				=> '由于工作力度与时间原因, 站点开放发帖时间为 {$GLOBALS[db_poststart]}:00 点到 {$GLOBALS[db_postend]}:00 点 !',
'post_allowtype'			=> '本版不允许发布该类型主题!',
'post_recycle'				=> '本版为回收站，不能发帖',
'vote_num_limit'			=> '投票选项个数超过最大限制（最大：{$GLOBALS[db_selcount]}个）。',
'notice_illegalid'			=> '无效公告ID',

'send_message_to_self'		=> '你不能给自己发消息',
'msg_ban_fail'				=> '屏蔽列表修改失败',
'msg_ban_success'			=> '完成屏蔽列表修改',
'msg_limit'					=> '发送失败:请不要在 {$GLOBALS[_G][postpertime]} 秒内连续性的发送短消息.',
'msg_num_limit'				=> '用户组权限：你今日发送的短消息不能超过{$GLOBALS[_G][maxsendmsg]}条',
'msg_subject_limit'			=> '标题不得大于75字节,内容不得大于1500字节',
'msg_empty'					=> '用户名，标题或内容为空.',
'msg_group_right'			=> '用户组权限：你所属的用户组没有发送短消息权限',
'msg_error'					=> '该信息已被删除',
'msg_unread_success'		=> '标记未读成功!',
'sebox_full'				=> '您的发件箱容量已满,请删除部分信息.',
'msg_send_limit'			=> '好友群发限制：每次最多只能给10位好友群发短消息!',

'member_right'				=> '用户组权限：你所属的用户组不能查看会员列表',

'mawhole_count'				=> '一次删除，复制或移动帖子不能超过500帖',
'mawhole_error'				=> '不能将帖子复制或移动到分类版块内',
'mawhole_nodata'			=> '没有要删除或移动的帖子数据',
'mawhole_beyondpushtime'	=> '您输入的帖子提前时间超出时间上限，请重新输入',
'mawhole_erropushtime'		=> '您输入了错误的提前时间',
'mawhole_right'				=> '您的等级不足,没有此管理权限',
'mawhole_notype'			=> '该版块没有设置主题分类',
'mawhole_color_error'		=> '颜色数据有误',
'mawhole_top_error'			=> '帖子置顶操作失败，请选择需要置顶的版块',
'mawhole_top_timeerror'		=> '置顶有效时间填写错误',
'admin_forum_right'			=> '你无权管理其他版块的帖子',
'mawhole_nodigest'			=> '请选择精华管理选项操作',
'area_push_right'			=> '你没有可推送的门户页面',

'cmsread_have_no_creat'		=> '本帖还没有启用cms形式阅读',
'masigle_nojinggao'			=> '没有警告可以取消',
'masigle_top'				=> '您没有管理分类置顶或总置顶的权限',
'masigle_point'				=> '不能超过您的评分上限，今天剩余评分点数为：<span class=\'s3 b\'>{$GLOBALS[leavepoint]}</span>',
'masigle_nopoint'			=> '您今天的评分点数已经用完，请明天再进行评分操作！',
'masigle_creditlimit'		=> '一次评分不能大于{$GLOBALS[markset][$GLOBALS[limitCreditType]][maxper]},或小于{$GLOBALS[markset][$GLOBALS[limitCreditType]][minper]}',
'masigle_credit_error'		=> '积分点数必须为数字',
'masigle_credit_right'		=> '你无权对此积分进行评分',
'masigle_manager'			=> '抱歉，不能给自己评分',
'masigle_ban_fail'			=> '禁言失败，{$GLOBALS[username]}不为会员组，只能禁言会员组',
'member_havebanned'			=> '用户 {$GLOBALS[username]} 已经被禁言',
'ajax_banuser_success'			=> '禁言<b>{$GLOBALS[username]}</b>成功！\treload',
'ajax_banfree_success'			=> '用户<b>{$GLOBALS[username]}</b>解禁成功！\treload',
'banuser_notfound'			=> '禁言用户<b>{$GLOBALS[username]}</b>没有找到！',
'banuser_no_banright'			=> '你没有权限执行禁言操作',
'masigle_ban_right'			=> '你没有永久禁言会员的权限',
'masigle_ban_limit'			=> '你能禁言用户的最大天数为{$GLOBALS[pwBanMax]}天',
'masigle_ban_range'			=> '你没有权限对会员进行全局禁言或封IP',
'masigle_nodata'			=> '没有要处理的评分记录',
'masigle_noping'			=> '错误操作,该帖还没有评分!',

'login_forbid'				=> '已经连续 6 次密码输入错误,您将在 10 分钟内无法正常登录,还剩余 $GLOBALS[L_T] 秒',
'login_pwd_error'			=> '密码错误或安全问题错误,您还可以尝试 $GLOBALS[L_T] 次',
'login_usernamepwd_error'	=> '用户名或密码错误,您还可以尝试 $GLOBALS[L_T] 次',
'login_safecv_error'		=> '安全问题错误,您还可以尝试 $GLOBALS[L_T] 次',
'login_jihuo'				=> '你的帐号没有激活，请先到您注册的电子邮箱里激活帐号!<br /><br />
								如果您的电子邮箱无法收到邮件，您可以点击这里，
								<a href="remail.php?uid=$GLOBALS[jihuo_uid]"><font color="blue">进行电子邮件重发!</font></a>',
'login_empty'				=> '用户名或密码为空',
'login_have'				=> '您已经为会员身份,请不要重复登录!',
'login_errortype'			=> '您的登录类型有误!',

'job_vote_num'				=> '投票个数超过指定个数',
'job_vote_leastnum'			=> '投票个数少于最少个数',
'job_vote_sel'				=> '没有选择投票项',
'job_havevote'				=> '您已经参与了这次投票,请不要作弊',
'job_vote_lock'				=> '投票失败,帖子已被锁定！',
'job_vote_right'			=> '用户组权限：你所属的用户组没有投票权限',
'job_vote_close'			=> '投票主题已关闭!',
'job_havebuy'				=> '您已经购买此帖.请不要重复!',
'sell_error'				=> '出售价格错误',
'job_buy_noenough'			=> '您的 {$GLOBALS[creditname]} 不足 {$GLOBALS[creditvalue]}，无法购买此帖!',
'job_viewtody_close'		=> '后台核心设置关闭统计.需要管理员打开统计才能使用此功能!',
'job_favor_del'				=> '没有指定删除收藏的主题!',
'job_favor_success'			=> '收藏成功!',
'job_favor_error'			=> '您已经收藏过了',
'job_favor_full'			=> '您的收藏夹已满，收藏夹最大容量为：{$GLOBALS[_G][maxfavor]}',
'job_attach_right'			=> '您无权限删除附件',
'job_attach_error'			=> '附件不存在',
'job_attach_rvrc'			=> '下载该附件需要：{$GLOBALS[needrvrc]}{$GLOBALS[creditName]}，
								您目前的{$GLOBALS[creditName]}：{$GLOBALS[usercredit]}',
'job_attach_rvrc_download'	=> '下载该附件需要：{$GLOBALS[needrvrc]}{$GLOBALS[creditName]}，<br />
								扣除附件下载所需积分{$GLOBALS[downloadmoney]}{$GLOBALS[creditName]}后,您目前的{$GLOBALS[creditName]}：{$GLOBALS[usercredit]}',
'job_attach_sale'			=> '该附件售价：{$GLOBALS[needrvrc]}{$GLOBALS[creditName]}，
								您目前的{$GLOBALS[creditName]}：{$GLOBALS[usercredit]}',
'job_attach_sale_download'	=> '版块下载附件需花费：{$GLOBALS[downloadmoney]}{$GLOBALS[creditName]}；<br />
								该附件售价：{$GLOBALS[needrvrc]}{$GLOBALS[creditName]}；<br />
								您的积分不足，目前拥有：{$GLOBALS[usercredit]}{$GLOBALS[creditName]}',
'job_attach_special'		=> '本附件为特殊附件，游客不能下载！',
'job_attach_group'			=> '用户组权限：你所属的用户组没有下载附件的权限',
'job_attach_forum'			=> '对不起，本版块只有特定用户可以下载附件，请返回',
'job_delimg_error'			=> '删除失败，您没有使用头像上传功能或上传头像数据错误',

'ip_change'					=> '用户密码已更改 或 站点开启了安全认证 , 需要重新登录!<br><br>如果您无法退出,请点选IE 工具->选项 然后手动清除COOKIE',

'no_right'					=> '不能订阅本版文章',
'have_report'				=> '该内容已经有人举报过',
'report_success'			=> '举报成功!',
'report_right'				=> '用户组权限：你所属的用户组不能使用报告功能',
'profile_right'				=> '用户组权限：你所属的用户组不能查看会员资料',
'no_markright'				=> '用户组权限：你所属的用户组没有评分权限.',
'markright_set_error'		=> '评分设置有误，请联系管理员检查本用户组的评分设置',
'pingtime_over'				=> '评分超时，你不能对此帖进行评分!',
'no_markagain'				=> '你已经评过分了，你所属的用户组没有重复评分的权限.',
'member_credit_error'		=> '评分点数错误，请输入一个大于或小于零整数.',

'forum_locked'				=> '该版块设置了锁定 {$GLOBALS[forumset][lock]} 天前的帖子，发帖日期超过 {$GLOBALS[forumset][lock]} 天的帖子将被锁定，不允许回复。',

'forum_creditlimit'			=> '<table style="width:100%">
	<tr><td colspan=2><b>该版块设置了限制积分访问，以下积分为访问该版块需要的最低积分要求</b></td></tr>
	<tr><td>积分要求</td><td>您现在的积分</td></tr>
	<tr>
	<td>{$GLOBALS[db_rvrcname]}：{$GLOBALS[forumset][rvrcneed]}</td><td>{$GLOBALS[db_rvrcname]}：{$GLOBALS[userrvrc]}</td></tr>
	<tr>
	<td>{$GLOBALS[db_moneyname]}：{$GLOBALS[forumset][moneyneed]}</td><td>{$GLOBALS[db_moneyname]}：{$GLOBALS[winddb][money]}</td></tr>
	<tr>
	<td>{$GLOBALS[db_creditname]}：{$GLOBALS[forumset][creditneed]}</td><td>{$GLOBALS[db_creditname]}：{$GLOBALS[winddb][credit]}</td></tr>
	<tr><td>发帖数：{$GLOBALS[forumset][postnumneed]}</td><td>发帖数：{$GLOBALS[winddb][postnum]}</td></tr>
	</table>',

'unenough_money'			=> '您的{$GLOBALS[creditname]}不足，不能购买相应的道具',
'unenough_currency'			=> '您的{$GLOBALS[creditname]}不足，不能购买相应的道具 <a href="userpay.php?action=buy"><img border="0" src="{$GLOBALS[db_picpath]}/post/rechargeable.png"></a>',
'unenough_nums'				=> '您要转让的道具数量大于您拥有的道具数量。',
'unenough_sellnum'			=> '您要购买的道具数量超过了用户出售的道具数量。',
'unenough_toolnum'			=> '您的道具数量不足,无法进行转让操作.',
'unenough_stock'			=> '您要购买的道具数量超过了该道具的系统库存数量。',
'no_stock'					=> '系统库存不足。',
'illegal_nums'				=> '您输入的数字为非法数字，请输入一个大于 “0” 的“整数”。',
'numerics_checkfailed'		=> '您提交的数据中包含非法数据,请返回重新操作.',
'empty_credit'				=> '请填写需要转换的积分。',
'noenough_currency'			=> '您的积分不足 <a href="userpay.php?action=change" target="_blank"><font color="blue">积分转换</font></a> <a href="userpay.php?action=buy"><font color="blue">积分充值</font></a>',
'change_credit_error'		=> '你要转换的积分超过你当前拥有的积分。',
'trade_close'				=> '管理员关闭了用户交易功能。',
'toolcenter_close'			=> '管理员关闭了道具中心功能。',
'neednt_unsell_tool'		=> '您没有转让该道具，无需取消转让',
'neednt_close_toolsell'		=> '您的道具店处于关闭状态，无需进行关闭操作',
'neednt_open_toolsell'		=> '您的道具店处于开启状态，无需进行开启操作',
'nonetool_cannt_open' 		=> '您目前没有任何道具，无需开启道具店',
'tool_close'				=> '对不起，该道具未启用，您不能使用该道具。',
'tool_buyclose'				=> '对不起，该道具未启用，您不能购买该道具。',
'tool_grouplimit'			=> '您所属的用户组禁止使用该道具',
'tool_creditlimit'			=> '您的积分没有达到道具的使用积分要求',
'tool_forumlimit'			=> '该版块禁止使用该道具',
'nothistool'				=> '您的道具箱中没有该道具',
'tool_authorlimit'			=> '对不起，该道具只对自己发表的帖子有效。',
'tool_error'				=> '使用道具时，传递的参数错误，请返回重试。',
'tooluse_type_error'		=> '该道具类型后台设置错误',
'tooluse_not_finished'		=> '道具文件不存在，文件名设置错误或该功能未完成',
'tooluse_nopig'				=> '不存在还原猪头的对像',
'tooluse_cantuse'			=> '该会员已经使用了护身符,不能对其使用猪头术',
'tooluse_nousepig'			=> '该用户未被使用猪头卡，还原卡失效',
'tooluse_nobirther'			=> '不存在送生日卡对像',
'tooluse_nodefender'		=> '不存在使用护身符的对像',
'tooluse_deused'			=> '该会员已经使用了护身符',
'tooluse_noiper'			=> '不存在查看IP的对像',
'toolmsg_success'			=> '{$GLOBALS[tooldb][name]}道具使用成功!',
'toolmsg_1_success'			=> '道具使用成功，已经将您的‘{$GLOBALS[db_rvrcname]}’负分转为 0。',
'toolmsg_1_failed'			=> '道具使用失败，您的‘{$GLOBALS[db_rvrcname]}’不是负分，不需要转换，您可以在以后有需要时使用此道具。',
'toolmsg_2_success'			=> '道具使用成功，已经将您的所有积分负分都已经转为 0。',
'toolmsg_2_failed'			=> '道具使用失败，您的积分中没有负分，不需要转换，您可以在以后有需要时使用此道具。',
'toolmsg_4_failed'			=> '道具使用失败，您的帖子已经在版块中置顶，不需要对这个帖子使用该道具。',
'toolmsg_5_failed'			=> '道具使用失败，您的帖子已经在分类中置顶，不需要对这个帖子使用该道具。',
'toolmsg_6_failed'			=> '道具使用失败，您的帖子已经在整个论坛置顶，不需要对这个帖子使用该道具。',
'toolmsg_8_success'			=> '道具使用成功，您的用户名已经改为 {$GLOBALS[pwuser]} 。',
'no_tool'					=> '您没有可以使用的道具，请先到 <a href="profile.php?action=toolcenter"><font color="blue">系统交易中心</font></a> 购买道具。',

'groupright_show'			=> '用户组权限，你所属的用户组没有使用展区功能。',
'showsign_error'			=> '后台没有开启此功能。',
'showsign_success'			=> '签名展示设置成功。',

'username_exists'			=> '该用户名已经被注册，请选用其他用户名。',
'username_not_exists'		=> '恭喜您，该用户名还未被注册，您可以使用这个用户名注册！',
'space_name_toolong'		=> '空间名称不能超过80个字符',
'space_descript_toolong'	=> '空间简介不能超过255个字符',


'photo_pintro_toolong'		=> '您所上传的照片描述太长',
'colony_close'				=> '管理员关闭了{$GLOBALS[cy_name]}功能。',
'colony_undefined'			=> '没有上传权限或相册不存在',
'colony_reglimit'			=> '系统不允许注册新的群组。',
'colony_groupright'			=> '用户组权限，你所在的用户组没有此权限。',
'colony_creatfailed'		=> '您的{$GLOBALS[moneyname]}不足，创建一个群组需要支付 {$GLOBALS[o_createmoney]} 个{$GLOBALS[moneyname]}',
'colony_numlimit'			=> '抱歉，提升你的会员组等级后才能创建更多群组！',
'colony_class'				=> '请选择群组的关联版块。',
'colony_emptyname'			=> '群组的名称不能为空，或是名称长度超过20字节。',
'colony_samename'			=> '您输入的群组名称已经存在，请选择另一个名称。',
'colony_joinlimit'			=> '加入群组失败，您允许加入的群组个数已满。',
'colony_memberlimit'		=> '加入群组失败，该群组人数已满。',
'colony_joinrefuse'			=> '该群组拒绝新成员加入。',
'colony_joinfail'			=> '您的{$GLOBALS[moneyname]}不足，加入群组需要 {$GLOBALS[o_joinmoney]} {$GLOBALS[moneyname]}',
'colony_passfail'			=> '用户 <b>{$GLOBALS[rt][username]}</b> {$GLOBALS[moneyname]}不足，不能通过审核。',
'colony_nocheck'			=> '您还没通过管理员审核，暂时不能使用群组功能。',
'colony_alreadyjoin'		=> '你已经加入了该群组。',
'colony_joinsuccess'		=> '加入群组成功！\treload',
'colony_joinsuccess_check'	=> '你的加入群组申请已提交，请等待群主审核\treload',
'colony_joinsuccess_check2'	=> '你的加入群组申请已提交，请等待群主审核',
'colony_outsuccess'			=> '退出群组成功！\treload',
'colony_cancelsuccess'		=> '解散群组成功！\tjump\t{$GLOBALS[basename]}q=groups',
'colony_cardright'			=> '你还不是这个群组的会员，不能查看名片夹！',
'colony_editcard'			=> '你还不是这个群组的会员，不能使用名片功能！',
'colony_nocard'				=> '你要编辑的名片不存在。',
'colony_noseecard'			=> '你要查看的名片不存在。',
'colony_boardright'			=> '你不是该群组的成员，无权访问该群组的讨论区。',
'colony_post'				=> '你还未通过审核，暂时无法发表新话题',
'colony_post2'				=> '你还未加入该群组，暂时无法发表新话题',
'colony_ajax_post'			=> '你还未加入该群组，暂时无法发表新话题,赶快<a onclick="sendmsg(\'apps.php?q=group&cyid={$GLOBALS[cyid]}&a=join\',\'\',\'\');" id="joincolony3" href="javascript:;">加入</a> 吧！',
'colony_reply'				=> '你还未通过审核，暂时无法回复话题',
'colony_reply2'				=> '你还未加入该群组，暂时无法回复话题',
'colony_posterror'			=> '标题或内容为空。',
'colony_editright'			=> '你没有权限编辑他人的帖子',
'colony_delright'			=> '你没有权限删除他人的帖子。',
'colony_donateright'		=> '你不是该群组的成员，不能使用此功能。',
'colony_donateerror'		=> '捐献的{$GLOBALS[moneyname]}数必须是大于零的整数。',
'colony_donatefail'			=> '捐献失败，您捐献的{$GLOBALS[moneyname]}数大于您拥有的{$GLOBALS[moneyname]}数',
'colony_donatesuccess'		=> '荣誉点提升成功！',
'colony_adminright'			=> '你不是群组管理员，不能使用此功能.',
'colony_sizelimit'			=> '你上传的图片太大超过了系统限制的大小。',
'colony_type_error'			=> '上传图片类型错误，只允许上传后缀名为 jpg,jpeg,png,gif,bmp 的图片',
'colony_lenthlimit'			=> '上传的图片必须在（0 - $GLOBALS[cn_imgheight] ）*（0 - $GLOBALS[cn_imgwidth] ）的大小范围里',
'colony_joinmoney'			=> '会员加入群组至少需要{$GLOBALS[moneyname]}个数：{$GLOBALS[cn_joinmoney]}',
'colony_addamin'			=> '管理员设置完成。',
'colony_delladminfail'		=> '不能取消群组创建者的管理员身份。',
'colony_deladmin'			=> '取消管理员完成。',
'colony_pass'				=> '审核会员完成。',
'colony_delfail'			=> '不能删除群组创建者。',
'colony_del'				=> '删除会员完成。',
'colony_cancelclose'		=> '系统关闭了解散群组的功能。',
'colony_cancel'				=> '你不是群组的创建者，无权解散该群组.',
'colony_unjoin'				=> '你还没有加入任何群组',
'colony_descrip'			=> '群组简介长度不能超过255字节!',
'colony_phopen'				=> '相册被系统管理员关闭，暂时无法使用!',
'colony_opentocn'			=> '此相册只对群组内部开放!',
'colony_opentome'			=> '此相册个人私有，他人无法观看!',
'colony_openlimit'			=> '本群组不对非正式成员开放',
'colony_del_members'		=> '你必须先删除所有成员，才能解散群组',
'colony_del_photo'			=> '必须删除群组下所有照片和相册才能解散',
'colony_viewcard'			=> '只有正式成员才能查看会员真实资料',
'colony_cnmenber'			=> '不是本群组成员，无法执行此操作',
'colony_creatalbum'			=> '你不是本群组成员，无法在此创建相册',
'colony_aname_empty'		=> '<span class=\'warnFontStyle\'>相册名</span>不能为空',
'colony_aname_toolang'		=> '<span class=\'warnFontStyle\'>相册名</span>不能超过<span class=\'warnFontStyle\'>24</span>个字符',
'colony_aintro_toolang'		=> '<span class=\'warnFontStyle\'>相册描述</span>不能超过<span class=\'warnFontStyle\'>255</span>个字符',
'colony_pubalbum'			=> '你不是管理员，不能创建公共相册',
'colony_moneylimit'			=> '群组没有足够的余额来创建相册',
'colony_album_num'			=> '相册数量达到最大，无法继续创建',
'colony_album_num2'			=> '你已经创建了足够多的相册，无法继续创建',
'colony_moneylimit2'		=> '你需要{$GLOBALS[moneyvalue]}{$GLOBALS[moneyname]}才能创建相册',
'colony_photonum'			=> '本相册下还存有图片，请先清空图片再删除相册',
'colony_editphoto'			=> '只有上传者自己才可以编辑照片',
'colony_albumclass'			=> '请选择照片所属的相册分类',
'colony_phototype'			=> '此相册为个人相册，你无权上传',
'colony_subject'			=> '标题长度不能大于50个字节',
'colony_photofull'			=> '此相册照片数量达到上限，无法上传',
'uploadphoto_leave'			=> '此相册容量不足,仅能上传{$GLOBALS[uploadlimit]}张!',
'colony_select_photo'		=> '请选择要导入的图片',
'colony_filetype'			=> '上传的不是一个图像文件',
'colony_filesize'			=> '上传图片大小超过限制',
'colony_uploadnull'			=> '上传图片不成功！请检查是否选择要上传的图片',
'colony_ifadmin'			=> '你无权执行此项操作',
'colony_update'				=> '该群组已经升级过，无法再次升级',
'colony_updatemoney'		=> '群组 资金不足,无法升级.',
'colony_topright'			=> '你没有权置顶此帖子。',
'colony_username_empty'		=> '用户名为空。',
'colony_transferfailed'		=> '你的{$GLOBALS[moneyname]}不足，转让一个群组需要支付 {$GLOBALS[cn_transfermoney]} 个{$GLOBALS[moneyname]}',
'colony_transferright'		=> '你不是创始人，不能转让群组',
'colony_transfer_same'		=> '你不能将群组转给自己',
'colony_user_notin'			=> '接受转让的用户不是该群组成员',
'colony_not_exists'			=> '该朋友圈不存在或搜索用户为空',
'colony_add_ignore'			=> '你已经忽略了对方的请求',
'colony_request_agree'			=> '你已经同意了TA的群组请求'	,

'friend_add_success'		=> '从现在开始，你们俩就是好友了！<a href="{$GLOBALS[db_userurl]}{$GLOBALS[fid]}">马上去看TA</a>',
'friend_add_fail'			=> '添加好友失败',
'friend_add_ignore'			=> '你已经忽略了对方的请求',
'friend_request_agree'		=> '你已经同意了TA的好友请求'	,

'app_add_success'			=> '你同意安装了此应用',
'app_add_fail'				=> '应用安装失败',
'app_add_ignore'			=> '你已经忽略了对方的请求',
'app_request_agree'			=> '你已经同意了TA的应用请求'	,

'request_friend'			=> '好友请求',
'request_group'				=> '群组请求',
'request_app'				=> '应用请求',
'request_ignore'			=> '你已经忽略了对方的请求',


'sale_error'				=> '交易帐号，商品名称，商品价格为空或格式错误！',
'seller_error'				=> '交易帐号格式错误',

'olpay_seterror'			=> '网上支付设置错误，请管理员登录后台“网上支付设置”检查设置是否正确！',
'olpay_tenpayerror'			=> '财富通信息设置错误，请管理员登录后台“网上支付设置”检查设置是否正确！',
'olpay_numerror'			=> '对不起，你输入的金额无效，请输入一个大于{$GLOBALS[paynum]}的数。（网络支付最低人民币：{$GLOBALS[paynum]} 元 ）',
'olpay_errortype'			=> '请选择充值的积分!',
'olpay_paypalerror'			=> '贝宝信息设置错误，请管理员登录后台“网上支付设置”检查设置是否正确！',
'olpay_alipayerror'			=> '交易信息设置错误，请管理员登录后台“网上支付设置”检查设置是否正确！',
'olpay_pay99error'			=> '快钱信息设置错误，请管理员登录后台“网上支付设置”检查设置是否正确！',
'alipay_failure'			=> '在线支付失败，请联系管理员',

'medal_close'				=> '系统没有开启勋章功能',
'medal_noreason'			=> '请输入操作原因！',
'medal_groupright'			=> '您所属的用户组没有颁发（收回）勋章的权限',
'medal_appgroupright'		=> '您所属的用户组没有申请勋章的权限',
'medal_haveapp'				=> '您有申请过的请求还未受到处理，不能再次申请',
'medal_alreadyhave'			=> '{$GLOBALS[erroruser]}已经拥有此勋章',
'medal_alreadyhaveself'		=> '您已经已经拥有此勋章',
'medal_none'				=> '{$GLOBALS[erroruser]}用户没有此勋章',
'medal_nouser'				=> '用户不存在，或者您的输入有误',
'medal_dellog'				=> '只有管理员才能删除勋章颁发日志',
'medal_nomedal'				=> '请选择要授予的勋章！',
'medal_iderror'				=> '数据有误，没有操作id',
'medal_appclose'			=> '未开启勋章申请功能',

'blog_close'				=> '系统没有开启博客功能',
'username_empty'			=> '用户名为空，请填写用户名！',

'colony_cnamelimit'			=> '群组名称太长，请控制在 20字节 以内',
'colony_cnamelimit_admin'	=> '群组名称太长，请控制在 50字节 以内',
'colony_descriplimit'		=> '群组简介不符，请控制在 1-255字节之间',
'colony_annoucelimit'		=> '群组公告太长，请控制在 50000字节 以内',

'virement_success'			=> '{$GLOBALS[moneyname]}转帐成功！',
'virement_lock'				=> '{$GLOBALS[moneyname]}转帐已被锁，请30秒后再使用此功能。',
'empty_password'			=> '请输入验证密码',
'password_error'			=> '密码验证失败，请输入正确的密码',
'virement_closed'			=> '系统没有开启积分转帐功能',
'currency_limit'			=> '系统设定最低转帐金额为：{$GLOBALS[db_virelimit]}',

'realname_limit'			=> '真实姓名长度错误，请控制在 20字节以内',
'tel_limit'					=> '电话长度错误，请控制在 15字节以内',
'intro_limit'				=> '个人简介太长，请控制在 255字节 以内',
'colony_manager'			=> '只有群组的创建者有添加和删除管理员的权限',
'colony_currency'			=> '系统没有开启群组{$GLOBALS[db_currencyname]}管理功能',
'colony_noenough_currency'	=> '群组的{$GLOBALS[moneyname]}不足，您可以使用捐献功能增加群组的{$GLOBALS[moneyname]}',
'no_colony_member'			=> '$GLOBALS[pwuser] 不是该群组的会员，此功能只允许给朋友圈中的会员增加{$GLOBALS[db_currencyname]}',
'colony_currency_right'		=> '只有群组创建者有权限管理群组的{$GLOBALS[db_currencyname]}。',

'sendmail_closed'			=> '系统没有开启邮件发送功能。',
'no_atclog_right'			=> '用户组权限：你所属的用户组不允许使用“查看帖子操作记录”的权限。',
'no_cstyles_right'			=> '用户组权限：你所属的用户组不允许使用“自定义风格”的权限。',
'cstyles_num_limit'			=> '用户组权限：你的自定义风格不能超过{$GLOBALS[_G][maxcstyles]}套。',
'no_viewright_right'		=> '用户组权限：你所属的用户组不允许使用“用户组权限查看”的权限。',
'mode_cstyles_right'		=> '模式下不允许使用自定义风格功能。',
'enterreason'				=> '请输入操作原因！',

'illegal_icon'				=> '引用头像链接不能超过85个字节',

'string_limit'				=> '您输入的信息字串太长，请控制在{$GLOBALS[_strmaxlen]}字节以内',
'field_lenlimit'			=> '您输入的“<b>{$GLOBALS[value][title]}</b>”太长，请控制在{$GLOBALS[value][maxlen]}字节以内',
'field_empty'				=> '“<b>{$GLOBALS[value][title]}</b>”为必填内容，请返回填写！',
'alipay_error'				=> '支付宝帐号格式有误！',

'special_allowbuy'			=> '该用户组身份不允许用户使用“{$GLOBALS[db_currencyname]}”购买。',
'special_selllimit'			=> '您要购买用户组身份的天数小于该用户组“最短购买天数”限制！',
'specialgroup_exists'		=> '您已经购买了该用户组身份，用户组身份到期时间：{$GLOBALS[enddate]}。',
'specialgroup_error'		=> '您要购买的用户组不存在。',
'specialgroup_noneed'		=> '您已经是该用户组成员，不需要购买！',

'gross_error'				=> '订单信息错误，请联系管理员解决！',
'passport_close'			=> '系统没有开启通行证功能。',
'passport_login'			=> '系统开启通行证功能，请到 <a href="$GLOBALS[loginurl]">通行证登录地址</a> 进行登录!',
'passport_register'			=> '系统开启通行证功能，请到 <a href="$GLOBALS[regurl]">通行证注册地址</a> 进行注册!',
'passport_safe'				=> '安全检验失败，请检查通行证设置是否正确！',
'passport_data'				=> '数据检验失败，缺少参数！lack_data',
'passport_error'			=> '数据检验失败，无效数据！expired_error',

'days_limit'				=> '您的邀请码已过期!',
'invcode_error'				=> '您要发送的邀请码不存在!',
'group_invite'				=> '您所在的组别没有购买邀请码的权限!',
'invite_costs'				=> '您的积分不足以购买邀请码!',
'invite_buy'				=> '最多只能购买10个邀请码!',
'inv_limitdays'				=> '邀请码购买时间限制，请稍侯',

'reward_noright'			=> '您没有权限管理其他人的悬赏帖!',
'reward_time_limit'			=> '悬赏时间没有超过规定时间，不能强制结案!',
'rewardmsg_success'			=> '你已经给斑主发送短消息，很快能得到答复!',
'reward_no_forumadmin'		=> '对不起，该斑块没有斑主，您的申请无法提交!',
'reward_have_sendmsg'		=> '您已经给版主发过消息了，请勿重复发短消息!',
'reward_have'				=> '热心助人奖只允许加一次,您已经为该会员加过热心助人奖了!',
'invcode_empty'				=> '本站开启了邀请注册功能，没有邀请码将无法正常注册!',
'illegal_invcode'			=> '邀请码已被注册，请重新获取!',
'read_shield'				=> '错误操作,该帖已被屏蔽!',
'read_unshield'				=> '错误操作,该帖没有被屏蔽!',
'masingle_data_error'		=> '链接地址条件不足!',
'masingle_banip_noright'	=> '您没有权限禁止IP',
'masingle_banip_ban'		=> 'IP:{$GLOBALS[readdb][userip]} 已被禁止',
'masingle_banip_free'		=> 'IP:{$GLOBALS[readdb][userip]} 已经恢复',
'ip_banned'					=> '错误操作，IP:{$GLOBALS[readdb][userip]} 已经被禁止',
'masingle_bansignature_noright' => '您没有权限禁止签名',
'masingle_bansignature_hasrecord' => '错误操作，该用户的签名已经被禁止',
'masingle_bansignature_norecord'  => '错误操作，该用户的签名未被禁止',
'masingle_bansignature_ban'	  => '已经成功禁止{$GLOBALS[readdb][username]}的帖子签名显示',			
'masingle_bansignature_free'  => '已经成功解除{$GLOBALS[readdb][username]}的帖子签名屏蔽',						
'masingle_noip'				=> '要禁止的IP地址不能为空',
'remind_data_empty'			=> '提示内容不能为空!',
'remind_length'				=> '提示内容过长，请删掉一些!',
'medallog_del_error'		=> '该勋章未到期，不能删除日志!',
'credit_limit'				=> '您设置的积分值不能小于系统规定的最小值!',
'reward_credit_limit'		=> '您的积分不足，无法进行此操作!',
'reward_credit_error'		=> '您的积分类型不合法!',
'reward_help_error'			=> '该帖没有剩余的热心助人积分可以奖励',
'reward_helped'				=> '该帖已设置过热心助人奖励',
'reward_add_end'			=> '该帖已得到最佳答案，无需追加悬赏!',
'force_tid_select'			=> '本版块开启强制主题分类功能,请选择文章分类!',
'unite_data_error'			=> '您输入的数据为空或不是数字!',
'unite_limit'				=> '特殊帖无法被合并!',
'unite_fid_error'			=> '不同版块的帖子无法被合并!',
'upload_money_limit'		=> '您的{$GLOBALS[creditname]}不足,无法上传附件!',
'download_money_limit'		=> '版块下载附件需花费：{$GLOBALS[downloadmoney]} {$GLOBALS[creditname]}，您的积分不足 ,无法下载附件!',
'time_out'					=> '已经超过截止日期，无法申请!',
'num_full'					=> '您申请的活动已经达到最大人数，无法再申请了!',
'apply_gender_error'		=> '您的性别不符合要求，无法申请!',
'have_act'					=> '您已经申请过该次活动了!',
'actid_view_error'			=> '您没有参加该次活动或者尚未被批准!',
'selid_illegal'				=> '请选择操作对象!',
'active_manager_right'		=> '您不是活动发起人，没有管理权限!',
'active_content_empty'		=> '活动详情不为空!',
'contact_empty'				=> '联系方式不能为空!',
'active_data_empty'			=> '必填数据不能为空，请认真填写!',
'starttime_limit'			=> '开始时间不得小于当前时间!',
'deadline_limit'			=> '报名截止日期不得小于当前时间!',
'deadline_endtime_limit'	=> '报名截止日期不得大于活动结束时间!',
'endtime_limit'				=> '活动结束时间不得小于开始时间',
'can_not_modify_start'		=> '活动已经开始，不能修改活动开始时间',
'can_not_end'				=> '活动不能提交前结束',
'active_num_limit'			=> '限制人数少于已参加的总人数!',
'rightwhere'				=> '您没有该版块的管理权限!',
'email_check'				=> '为避免无法收到论坛信件，请使用指定电子邮箱进行注册!',
'email_bancheck'			=> '为避免无法收到论坛信件，电子邮箱({$GLOBALS[regemail]})无法进行注册!',
'remail_error'				=> '您还不是本站会员，或者已经通过验证!',
'remail_rgemail_error'		=> '您填写的电子邮箱与注册的电子邮箱不符，请重新填写!',
'remail_success'			=> '电子邮件重发完成，请查收!',
'not_forumadmin'			=> '您不是版主或者不是该版块的版主!',
'inv_close'					=> '站点没有开启邀请注册功能!',
'all_credit_error'			=> '积分类型错误!',
'credit_enough'				=> '您没有足够的积分进行此操作!',
'have_not_showping'			=> '错误操作,你没有给该帖评分!',
'sel_error'					=> '请选择操作对象!',
'tid_favor_error'			=> '该帖已收藏!',
'favor_cate_error'			=> '分类名称为空，或者长度超过20个字符!',
'favor_cate_limit'			=> '分类名称不能含有 “,” 字符!',
'type_error'				=> '你要删除的分类不存在!',
'illegal_request'			=> '非法请求，请返回重试!',
'ftp_not_exists'			=> '您的 php 不支持 ftp ,请到后台关闭 ftp 功能!',
'content_same'				=> '请勿连续发表相同内容的主题!',
'tofriend_msgerror'			=> '标题和内容不能为空,请填写!',
'illegal_imgtype'			=> '非法图片类型',
'pic_not_exists'			=> '该图片地址不存在或者没有权限查看该图片！',
'forum_not_allow'			=> '没有权限查看该版块',
'ftp_connect_failed'		=> '连接 ftp 服务器失败，请检查：<br />1、服务器地址和端口是否设置正确！ 2、网络是否通畅！',
'ftp_user_failed'			=> 'ftp 帐号错误！',
'ftp_pass_failed'			=> 'ftp 密码错误！',
'ftp_cwd_failed'			=> '访问文件夹出错，请检查服务器上 “ftp上传目录” 是否已建立！',
'email_fail'				=> '电子邮件发送失败!',
'email_invite_success'		=> '注册码购买完成，请进入电子邮箱查收!',
'email_connect_failed'		=> '连接电子邮件服务器失败，请检查：<br />1、服务器地址和端口是否设置正确！ 2、网络是否通畅！',
'email_user_failed'			=> '电子邮箱帐号错误！',
'email_pass_failed'			=> '系统用来发送邮件的电子邮箱密码错误！',
'email_from_failed'			=> '发信人地址错误！',
'email_toemail_failed'		=> '收信人地址错误！',
'email_data_failed'			=> '数据发送失败！',
'leaveword_error'			=> '您没有该帖留言的管理权限!',
'leaveword_right'			=> '用户组权限：您没有留言权限',
'save_success'				=> '保存成功!',
'delete_success'			=> '删除成功!',
'update_success'			=> '更新成功!',
'draft_full'				=> '您的草稿箱已满',
'draft_right'				=> '用户组权限：您没有草稿箱使用权限',
'have_login'				=> 'success\t您已经顺利登录',
'send_success'				=> '发送成功!',
'draft_error'				=> '您的草稿箱为空',
'content_empty'				=> '内容不能为空',
'operate_success'			=> '操作成功!',
'dig_success'				=> '感谢您对该帖的认同，帖子推荐成功!\t{$GLOBALS[read][dig]}',
'forum_dig_allow'			=> '该版块没有开放推荐功能!',
'dig_right'					=> '用户权限不足，您可以购买相关道具进行此操作。',
'dig_limit'					=> '您已经推荐这篇帖子了。',

'debate_time'				=> '辩论结束时间不能小于当前时间',
'debate_titlelen'			=> '辩论正方或反方的观点字数不能大于255字节',
'debate_noumpire'			=> '裁判必须为论坛注册会员',
'debate_notitle'			=> '辩论必须要有正方或反方的观点',
'debate_over'				=> '辩论已经结束',
'debate_voted_Y'			=> '您已经对正方观点表示支持，不可重复投票。',
'debate_voted_N'			=> '您已经对反方观点表示支持，不可重复投票。',
'debate_voted'				=> '您已经对此观点表示支持，不可重复投票。',
'debate_success'			=> '投票成功\tTID\t{$GLOBALS[debate][obvote]}\t{$GLOBALS[debate][revote]}\t{$GLOBALS[tmpob]}\t{$GLOBALS[tmpre]}\t{$GLOBALS[standpoint]}',
'debate_agree'				=> '投票成功\t{$GLOBALS[vote]}',
'debate_voteself'			=> '您不能对自己观点进行投票。',
'debate_pointlen'			=> '裁判点评字数不能大于255字节',
'debate_judgesuccess'		=> '裁判点评完成，辩论结束',

'safecv_prompt'				=> '系统强制您所在的用户组必须设置安全问题，请先到<a href="profile.php?action=modify" target="_blank"><b>控制面板</b></a>设置安全问题后再进行其他操作',
'pwdchange_prompt'			=> '系统强制您所在的用户组必须在一段时间后修改密码，请先到<a href="profile.php?action=modify" target="_blank"><b>控制面板</b></a>修改密码后再进行其他操作',
'safecv_prompt'				=> '系统强制您所在的用户组必须设置安全问题，请先到<a href="profile.php?action=modify" target="_blank"><b>控制面板</b></a>设置安全问题后再进行其他操作',
'friend_update_success'		=> '成功将对方加为好友',
'ajax_friend_update_success'=> '成功将对方加为好友\treload',
'friend_selferror'			=> '没必要搜索自己的名字吧，换一个',
'friend_self_add_error'		=> '不能加自己为好友',
'attention_self_add_error'		=> '不能加自己为关注',
'friend_not_exists'			=> '没有你要查找的用户',
'friend_status_error'		=> '您要访问的链接无效，可能链接不完整,或数据已被删除!',
'friend_already_exists'		=> '该用户已经在您的好友列表中。',
'attention_already_exists'	=> '该用户已经在您的关注列表中。',
'friend_already_exists_noaddattention'		=> '该用户已经是你的好友，所以无需关注',
'friend_status_check'		=> '该用户已经添加为好友，正在等待好友验证。',
'friend_not_add'			=> '该用户拒绝任何人加为好友。',
'friend_add_check'			=> '请求添加为好友，正在等待好友验证。',
'ajax_friend_add_check'			=> '请求添加为好友，正在等待好友验证。\treload',
'friend_nofind'				=> '没有找到你要的好友信息',
'friend_delete'				=> '成功解除好友。',

'tag_closed'				=> '系统没有开启标签功能',
'tags_num_limit'			=> '标签的数量请不要超过 <font color="red">5</font>个',
'tag_length_limit'			=> '标签的长度请控制在 <font color="red">3-15</font> 个字节之间',
'marked_success'			=> 'success\t评分成功!',
'unmarked_success'			=> 'success\t评分取消成功!',
'ajax_mawhole_operate_success' 		=> '操作成功!\tjump\tthread.php?fid=$GLOBALS[fid]',
'ajax_operate_success'		=> "操作成功!",
'ajax_unite_success'		=> '操作成功!\tjump\tread.php?tid=$GLOBALS[totid]',
'ajax_nextto'				=> '操作成功!\tnextto\tmawhole.php?action=$GLOBALS[nextto]&fid=$GLOBALS[fid]&ajax=1\tseltid=$GLOBALS[selids]\t$GLOBALS[nextto]',
'ajaxma_success'			=> '操作成功!\treload',
'tag_limit'					=> '该标签没关联文章！',
'per_error'					=> '不能查看用户组权限',
'id_error'					=> '没有选择操作对象',
'sharelink_colse'			=> '自助友情链接已关闭',
'sharelink_link_empty'		=> '站点名称和地址不能为空',
'sharelink_link_error'		=> '站点地址格式错误,必须以http://开头',
'sharelink_apply_limit'		=> '您已经提交过申请，每个会员只能提交一次申请',
'sharelink_success'			=> '友情链接申请成功，管理员后台通过审核才能在前台显示',
'newrp_error'				=> '您的回复列表为空',
'forum_allowtime'			=> '该版块在该时间段不允许发表帖子',
'jfchange_empty'			=> '论坛没有开启积分转换功能',
'commend_close'				=> '该版块没有开启版主推荐功能',
'commend_exists'			=> '该帖子已在推荐列表中',
'commendnum_limit'			=> '推荐帖子数目已经超过最大数目限制',
'change_error'				=> '您要兑换的积分数量必须为 {$GLOBALS[jf_A][$GLOBALS[type]][0]} 的整数倍',

'forumcp_recycle_maxcount'	=> '一次操作不能超过500帖',
'forumcp_recycle_nodata'	=> '没有要删除的帖子数据',
'annouce_title'				=> '公告标题不能为空',
'annouce_content'			=> '公告内容不能为空',
'annouce_fid'				=> '请选择公告发布的范围',
'annouce_time'				=> '结束时间必须大于起始日期',

'forummsg_object'			=> '请选择留言对象',
'forummsg_content'			=> '留言内容不能为空',
'forummsg_nodata'			=> '请选择需要删除的留言',

'advert_days_error'			=> '您申请的天数格式有误，请重新填写!',
'advert_lack_credit'		=> '您的积分不足，无法购买广告位,请 <a href="userpay.php?action=buy">充值积分</a>',
'advert_link_error'			=> '链接地址有误，请填写有效地址',
'advert_img_error'			=> '图片地址有误，请填写有效地址',
'advert_title_empty'		=> '文字内容为必填项',
'advert_discrip_empty'		=> '广告描述为必填项',
'advert_length_error'		=> '数据过长，请控制在100字节之内',
'advert_success'			=> '申请完成，请等待管理员的审核',

'shortcutok'				=> '您已成功将本版块加入到我的收藏夹!\tsuccessok',
'shortcutno'				=> '您已成功将本版块移除出我的收藏夹!\tsuccessno',
'shortcut_numlimit'			=> '您的书签个数已到最大值',

'space_over_right'			=> '您不是该空间主人，没有权限进行此操作!',

'element_can_not_construct'	=> '本对象无法直接实例化!',

'creditpay_empty'			=> '系统没有设置充值积分!',
'onlinepay_haspay'			=> '该订单已经支付!',
'onlinepay_goodsbuy'		=> '不能购买自己出售的商品!',
'onlinepay_goods_address'	=> '请务必填写收获地址、收获人和联系电话!',
'onlinepay_logistics'		=> '请填写物流信息!',
'goods_transport'			=> '请选择运送方式',
'onlinepay_alipay' 			=> '卖家未填支付宝帐号!',
'goods_num_error'			=> '填写的商品数量有误!',
'goods_pay_error'			=> '请填写收款方式!',
'goods_setprice'			=> '输入的商品价格格式不正确!',
'goods_logistics'			=> '请设置运费价格!',

'no_cateid'					=> '频道ID有误，请确认参数为有效数字',
'not_is_category'			=> '本频道不存在',
'push_must_img'             => '推送的帖子中必须有图片',
'ajax_push_success'			=> '您已成功的实现推送操作!',
'push_del_empty'			=> '没有选择内容',
'push_group_right'			=> '用户组权限：您所属的用户组没有推送的权限',
'push_del_group_right'		=> '用户组权限：您所属的用户组没有删除推送的权限',
'beyond_sql_max_size'		=> '主题分类的字节数超出数据库字段最大值',

'element_function_must'		=> '请去后台设置标签：{$GLOBALS[name]}所调用的模块',
'undefined_function'		=> '函数：{$GLOBALS[func]} 未定义',
'elementcache_scr_empty'	=> 'scr参数为必须参数',
'mode_cache_file_error'		=> '缓存文件调用出错',
'scr_not_defined'			=> 'SCR参数未定义',
'mode_template_pw_no_id'	=> 'pw 标签缺少唯一标识符:id',
'mode_temlate_id_error'		=> '参数：{$GLOBALS[id]} 包含非法字符',
'mode_stamp_block_error'	=> '模块分类设置数据有误，请先更新后台缓存再进行操作',
'mode_stamp_not_exist'		=> '模块分类：{$GLOBALS[stamp]}不存在',
'no_aim_to_push'			=> '没有可供推送的位置',
'minimage_wh_error'			=> '请设置图片的缩略宽度和高度',

'mode_o_no_share'			=> '该分享不存在',
'mode_o_delshare_permit_err'=> '您没有权限删除别人的分享',
'mode_o_not_friend'			=> '该会员还未和你结交为好友，您无法查看其资料',
'mode_o_is_friend'			=> '你们已经是好友了',
'mode_o_not_uid'			=> '缺失必要参数：好友uid',
'mode_o_email_toolang'		=> '电子邮件数据过多',
'mode_o_email_toomor'		=> '最多只支持同时发送5个电子邮箱',
'mode_o_email_empty'		=> '电子邮件地址不能为空',
'mode_o_email_format_err'	=> '电子邮件地址格式有误，请核实了再提交',
'mode_o_addftype_name_leng'	=> '好友分类名称的长度为1～20',
'mode_o_collectftype_name_leng'	=> '收藏分类名称的长度为1～20',
'mode_o_collectftype_name_exist'	=> '收藏分类名称已存在',
'mode_o_addftype_length'	=> '最多只能创建20个好友分类',
'mode_o_addftype_name_exist'=> '本好友分类名称已经存在',
'mode_o_extra_toolang'		=> '邀请附言字数不得多于200个',
'mode_o_board_self'			=> '不能自己给自己留言',
'mode_o_board_not_friend'	=> '你们还未成为朋友，无法发表留言',
'mode_o_board_too_lang'		=> '留言字数必须在3～200之间',
'mode_o_find_uid_err'		=> '搜索的uid只能是数字，且不能为空',
'mode_o_find_self'			=> '没必要搜索自己的名字吧，换一个',
'mode_o_invite_hash_error'	=> '会员验证码错误，无法查看本页面!',
'mode_o_invite_have'		=> '本站开启了邀请注册，请使用邀请码邀请好友',
'mode_o_invite_reg'			=> '本站已关闭了注册，无法使用邀请好友功能',
'mode_o_com_title_error'	=> '评论内容必须在3～200个字节之间',
'mode_o_com_del_priv'		=> '你无权删除别人的评论',
'mode_o_com_count_max'		=> '本应用的评论已达到上限：100',
'mode_o_write_success'		=> '发表成功!\treload',
'mode_o_write_del_error'	=> '删除的ID已不存在',
'mode_o_write_del'			=> '删除成功!\treload',
'mode_o_write_right'		=> '该朋友的记录设置了查看权限',
'mode_o_write_textminlen'	=> '内容字数不得少于3字节',
'mode_o_write_textmaxlen'	=> '内容字数不得多于255字节',
'mode_o_write_sametext'		=> '不能连续发表相同内容',
'mode_o_write_timelimit'	=> '30秒内只能发表一次内容',
'mode_share_link_error'		=> '链接地址出错，必须是正确的网址，且以“http://”开头',
'mode_share_descrip_toolang'=> '分享描述，必须在300字节之内',
'mode_o_invite_close' 		=> '系统未开启好友邀请',
'admin_delete_msg' 			=> '短消息可能已被管理员删除',

//7.0 End
//7.3.2
'mode_o_adddtype_name_leng' => '日志分类名称的长度为1～20字节',
'mode_o_adddtype_name_exist'=> '本日志分类名称已经存在',
'mode_o_adddtype_length'	=> '最多只能创建20个日志分类',
'mode_o_no_diary'			=> '该日志不存在',
'mode_o_deldiary_permit_err'=> '您没有权限删除别人的日志',
'mode_o_copy_permit_err'	=> '您无权转载该日志',
'diary_content_same'		=> '请勿连续发表相同内容的日志!',
'postfunc_urlnum_limit'		=> '您的发帖数未到{$GLOBALS[db_posturlnum]}，不能发表带有链接地址的帖子！',
'postgroup_urlnum_limit'	=> '您的发帖数未到{$GLOBALS[_G][posturlnum]}，不能发表带有链接地址的帖子！',
'job_vote_regdatelimit'		=> '您的注册日期小于此投票所设置的最小注册时间（$GLOBALS[regdatelimit]）,不能进行投票',
'job_vote_creditlimit'		=> '您的积分不足,不能进行投票',
'job_vote_postnum'			=> '您的发帖数小于{$GLOBALS[postnumlimit]},不能进行投票',
'album_pintro_toolang'		=> '照片描述不能超过255个字符',
'postdiary_check'			=> '您还没通过管理员验证,需要通过管理员验证才能发日志！',
'post_newd_limit'			=> '新注册用户{$GLOBALS[db_postallowtime]}分钟内不能发日志！',
'diary_group_right'			=> '用户组权限：你所属的用户组没有发表日志的权限!',
'photos_group_right'		=> '用户组权限：你所属的用户组没有创建相册的权限!',
'share_group_right'			=> '用户组权限：你所属的用户组没有分享权限!',
'weibo_group_right'			=> '用户组权限：你所属的用户组没有发表新鲜事的权限!',
'diary_gp_limit'			=> '用户组权限：你所属的用户组每日最多能发 {$GLOBALS[o_diarylimit]} 篇日志.',
'diary_limit'				=> '灌水预防机制已经打开，在{$GLOBALS[o_diarypertime]}秒内不能发日志',
'dairy_close'				=> '对不起！日志应用已关闭!',
'groups_close'				=> '对不起！群组应用已关闭!',
'share_close'				=> '对不起！分享应用已关闭',
'photos_close'				=> '对不起！相册应用已关闭',
'hot_close'					=> '对不起！ 热榜应用已关闭',
'hot_popedom'				=> '对不起！ 您没有权限访问',
'ban_content'				=> '用户被禁言，不能浏览内容',
'o_feedfriend_success'		=> '特定好有动态显示设置成功！',

'tpl_not_exist'					=> '该模板类型不存在',
'invoke_insert_data_error'		=> '模块数据插入有误',
'invoke_parse_error'			=> '模块解析出错',
'invoke_descrip_data_error'		=> '描述超过大小限制',
'invokepiece_insert_data_error'	=> '模块元素数据插入有误',
'data_is_not_array'				=> '操作数据必须为数组',
'load_class_error'				=> '无法调用{$GLOBALS[className]}类，可能是该文件不存在',
'tpl_insert_data_error'			=> '原始模块数据插入有误',
'parse_pw_error'			=> '{$GLOBALS[val]}模块解析出错，请确保后台有该模块存在',
'invoke_title_have_exist'	=> '模块名称有重复',
//7.3.2 End
'advert_have_show'			=> '您购买的广告正在展示中',
'advert_time_end'			=> '您购买的广告天数超过广告位到期时间',
'ipstates_not_open'			=> '未开启IP统计功能',
'select_no_friend'			=> '没有选择好友',
'photo_password_minlimit'	=> '相册密码最小3字节，最大15字节',
'photo_password_add'		=> '请输入密码',
'mode_o_photos_private_0'	=> '此相册不存在',
'mode_o_photos_private_1'	=> '该相册仅好友可见，您没有权限浏览.',
'mode_o_photos_private_2'	=> '该相册是私密的，您没有权限浏览.',
'mode_o_photos_private_3'	=> '该相册已加密，请输入正确密码.',
'app_type_worong'			=> '更新应用统计的应用类型错误',
'mutiupload_photofull'		=> '此相册照片数量达到上限，无法继续上传',
'select_ablum'				=> '请先选择相册',
'mode_o_diary_right'		=> '该朋友的日志设置了查看权限',
'mode_o_photos_right'		=> '该朋友的相册设置了查看权限',
'friend_type_not_exists'	=> '该好友分类不存在',
'pushdata_limit'			=> '自定义的数据已经超过该模块最大的显示个数',
'browse_close'				=> '随便看看模块已被关闭，暂时无法查看！',
'no_friend'					=> '目前还没有好友！',
'mode_o_index_right'		=> '由于对方的隐私设置，您没有权限查看。',
'app_close'					=> '应用被关闭',
'mail_close'				=> '发送邮件功能被关闭',
'readlog_data_error'		=> '最近没有帖子浏览记录',

//7.5RC end
'forum_topic_undefined'		=> '此主题不属于该版块',
'forum_model_undefined'		=> '此模板不属于该版块',
'forum_pc_undefined'		=> '该类型未开启或者不存在',
'topic_cate_unable'			=> '该主题未开启',
'topic_model_unable'		=> '该模板未开启',
'topic_field_must'			=> '{$GLOBALS[db_topicname]}为必填项',
'topic_number_limit'		=> '数字类型：{$GLOBALS[db_topicname]}超出范围值',
'topic_search_none'			=> '至少输入一个搜索条件',
'topic_search_forum'		=> '请选择正确的搜索信息',
'field_not_select'			=> '没有选择字段',
'field_not_exists'			=> '字段不存在',
'field_cannot_modify_index'	=> '该字段类型不能添加索引',
'field_key_have_exists'		=> '该字段已加索引',
'field_key_not_exists'		=> '该字段没有索引',
'fieldtype_not_exists'		=> '没有选择字段类型',
'copy_field_success'		=> "字段复制完成\tjump\t{$GLOBALS[basename]}&action=editmodel&cateid={$GLOBALS[cateid]}&modelid={$GLOBALS[modelid]}",
'field_add_success'			=> "字段添加完成\tjump\t{$GLOBALS[basename]}&action=editmodel&cateid={$GLOBALS[cateid]}&modelid={$GLOBALS[modelid]}",
'field_edit_success'		=> "字段添加完成\tjump\t{$GLOBALS[basename]}&action=editmodel&cateid={$GLOBALS[cateid]}&modelid={$GLOBALS[modelid]}",
'topic_add_success'			=> "主题添加完成\tjump\t{$GLOBALS[basename]}&action=editmodel&cateid={$GLOBALS[cateid]}&modelid={$GLOBALS[modelid]}",
'topic_edit_success'		=> "主题编辑完成\tjump\t{$GLOBALS[basename]}&",
'pcfield_add_success'		=> "字段添加完成\tjump\t{$GLOBALS[basename]}&action=editmodel&pcid={$GLOBALS[pcid]}",
'pcfield_edit_success'		=> "字段编辑完成\tjump\t{$GLOBALS[basename]}&action=editmodel&pcid={$GLOBALS[pcid]}",
'field_have_exists'			=> "字段变量名已经存在",
'pcjoin_nextstep'			=> '操作成功!\tnextto\tpw_ajax.php?action=$GLOBALS[nextto]&tid=$GLOBALS[tid]&thelast=1\tpcid=$GLOBALS[pcid]&pcmid=$GLOBALS[pcmid]&deposit=$GLOBALS[deposit]&nums=$GLOBALS[nums]&totalcash=$GLOBALS[totalcash]&payway=$GLOBALS[payway]\t$GLOBALS[nextto]',
'pcjoin_success'			=> "恭喜您，报名成功\treload",
'pcjoin_ownnotjoin'			=> "发起人无法参与报名",
'pcjoin_nums'				=> '报名人数错误或者不能为0',
'pcjoin_pcid_nums'			=> '购买数错误或者不能为0',
'pcjoin_pay'				=> "恭喜您，支付成功\treload",
'pcjoin_payed'				=> "操作错误，已经支付",
'pcjoin_end'				=> "已结束，不能再支付！",
'pcjoin_more'				=> "您报的人数已超总人数",
'pcjoin_pcid_more'			=> "您购买数量已超总数",
'pcjoin_mobile_error'		=> "真实姓名和手机必填",
'pclimitnum_error'			=> "您填写的数至少大于$GLOBALS[limitnums]",
'pcsendmsg_empty'			=> '主题和内容不能为空！！',
'pcexport_none'				=> '您无权使用此功能！',
'pcalipay_haspay'			=> '您已经支付！',
'number_error'				=> '数字、取值范围类型只允许填写数字',
'telphone_error'			=> '电话、人数限制只允许填写整数',
'numeric_error'				=> '<font color="red">价格、押金</font>只允许填写数字类型',
'joinpc_error'				=> '报名已经结束，不能修改',
'can_not_modify_field_type'	=> '有数据的字段不可修改字段类型',
'begin_endtime'				=> '截止时间必须大于发起时间！',
'pcpay_noright'				=> "您没有确认支付的权限",
'field_descrip_limit'		=> '描述不能超过255字节',
'showping_content_too_long'	=> '评分描述不能超过100字节',
'showping_maxcredit'		=> '单次评分超过上限',
'selid_error'				=> '没有选择用户',
'guest_notcard'				=> '该用户是游客身份发帖，没有名片信息',
'stopic_htm_is_not_777'		=> '请确保静态HTML目录为可写状态',
'colony_out_right'			=> '没有权限解散群组',
'colony_out_admin'			=> '您是群创始人，无法退出群组，您可以进入管理设置，转让或解散群!',
'diary_friend_right'		=> '该日志仅好友可见',
'app_not_register'			=> '本站点未注册APP',
'pcsendmsg_fail'			=> '还没有用户报名，不能群发消息',
'share_privacy'				=> '此日志为私密日志，不能分享',
'field_number_error'		=> '最小值不能大于最大值',
'field_number_numerror'		=> '范围值必须全填或者都留空',
'model_mustone'				=> '不允许删除最后一个模板',
'calendar_error'			=> '开始时间不准大于结束时间',
'field_rules_error'			=> '选项内容的格式错误',
'urlcheck_toomany'			=> "发布失败，内容中限制最多包含  <font color=\'red\'>{$GLOBALS[db_urlchecklimit]}</font> 个链接",
'urlcheck_inblack'			=> "发布失败，内容中的外链 <font color=red>'{$GLOBALS[blackurl]}'</font> 在黑名单中，禁止发布",


'userbinding_same'			=> '不能绑定本帐号，请选用其他帐号绑定!',
'switchuser_error'			=> '你绑定的帐号密码已修改，请解除后重新绑定!',
'userbinding_has'			=> '该帐号已绑定，请不要重复操作!',

'app_siteappkey_notexist'	=> '你好，该论坛尚未同APP平台关联，无法使用任何来自APP平台的应用!',
'post_allowpost'			=> '您无权发布该类型主题',
'app_not_blooming_class'	=> '对不起，帖子分类不存在，无法执行此功能',
'post_word_check'			=> '你发布的内容包含敏感词“{$GLOBALS[banword]}”，请等待管理员审核!',
'post_link_check'			=> '文章发表成功，但内容中链接个数过多，帖子需管理员审核通过后才能显示',
'colony_aname_also'			=> '相册名不能重复',
'colony_album_memopen'      => '此相册你无权上传',
'colony_topicadmin'			=> '您没有对该话题具有管理权限',
'colony_topicadmin_other_colony'=> '您没有权限管理其他群组的话题',
'thread_toptopic_success_ajax'	=> '置顶操作成功！\treload',
'toptopic_success'			=> '置顶操作成功！',
'thread_digest_success_ajax'	=> '精华操作成功！\treload',
'thread_lock_success_ajax'	=> '锁定操作成功！\treload',
'thread_pushtopic_success_ajax'	=> '提前操作成功！\treload',
'thread_downtopic_success_ajax'	=> '压帖操作成功！\treload',
'thread_type_success_ajax'	=> '分类操作成功！\treload',
'digest_success'			=> '精华操作成功！',
'lock_success'				=> '锁定操作成功！',
'pushtopic_success'			=> '提前操作成功！',
'downtopic_success'			=> '压帖操作成功！',
'deltopic_success_ajax'		=> '话题删除操作成功！\tjump\tapps.php?q=group&a=thread&cyid={$GLOBALS[cyid]}',
'thread_deltopic_success_ajax'	=> '话题删除操作成功！\tjump\tthread.php?cyid={$GLOBALS[cyid]}',
'deltopic_success'			=> '话题删除操作成功！',
'colony_type'				=> '群组分类设置不正确',
'no_selected_topic'			=> '没有选择话题',
'no_selected_topic'			=> '没有选择话题',
'delreply_success'			=> '回复删除操作成功！\treload',
'active_title_length'		=> '活动名称超过{$GLOBALS[db_titlemax]}字节',
'active_address_length'		=> '活动地址超过{$GLOBALS[db_titlemax]}字节',
'active_introduction_length'=> '活动介绍超过130字节',
'gwrite_closed'				=> '新鲜事已关闭',
'gactive_closed'			=> '群活动已关闭',
'gthread_closed'			=> '群话题已关闭',
'galbum_closed'				=> '群相册已关闭',
'highlight_success'			=> '加亮操作成功！',
'thread_highlight_success_ajax'	=> '加亮操作成功！\treload',
'colony_aname_length'		=> '相册名称不能超过24字节',
'colony_aintro_length'		=> '相册描述不能超过255字节',
'operate_success_reload'	=> '操作成功!\treload',
'colony_setunable'			=> '没有管理权限！',
'report_own'				=> '举报的内容是自己的，不能举报！',
'mawhole_notopped'			=> '请选择置顶管理选项操作',
'mawhole_nolock'			=> '请选择锁定管理选项操作',
'invite_user_not_exist'		=> '发起邀请的用户不存在！',
'active_atc_content_length'	=> '活动详情超过50000字节',
'colony_realname_too_long'  =>  '真实姓名不能超过20个字节',
'colony_tel_too_long'		=>  '电话号码不能超过15个字节',
'colony_email_too_long'		=>  '电子邮箱地址不能超过50个字节',
'colony_address_too_long'   =>  '联系地址不能超过255个字节',
'colony_introduce_too_long' =>  '介绍说明不能超过255个字节',
'colony_invite_message'		=>  '邀请好友发送消息成功，好友{$GLOBALS[inColonyUsers]}已经在该群组中',
'colony_invite_no_message'	=>  '好友{$GLOBALS[inColonyUsers]}已经在该群组中',
'space_not_exist'			=>  '您访问的空间不存在',
'space_is_not_viewright'	=>  '该空间设置隐私，您没有权限查看',
'user_notvisited'			=>  '您的帐号被禁用，无法访问本站点',

//活动
'selection_not_int'			=> '选项<b>{$GLOBALS[db_actname]}</b>的值为非整数',
'checkbox_not_array'		=> '多选框<b>{$GLOBALS[db_actname]}</b>的值不是数组',
'act_number_error'			=> '<b>{$GLOBALS[db_actname]}</b>的值必须为数值',
'calendar_wrong_format'		=> '<font color="red">{$GLOBALS[db_actname]}</font>不是合法的日期格式',
'act_field_must'			=> '<font color="red">{$GLOBALS[db_actname]}</font>为必填项',
'act_number_limit'			=> '数字类型：<font color="red">{$GLOBALS[db_actname]}</font>超出范围值',
'act_recommend_success'		=> '活动推荐成功!',
'act_recommend_fail'		=> '活动推荐失败',
'act_signup_time_error'		=> '已不在报名时间内',
'act_signup_iscertified_error'=> '活动尚未认证，无法报名',
'act_signup_iscancel_error'	=> '活动已取消，无法报名',
'act_signup_batch_no_error'	=> '活动号尚未创建，无法报名',
'act_signup_owner_error'	=> '发起人无法参与报名',
'act_signupnums_error'		=> '报名人数至少为1人',
'act_signupnums_error_max'	=> '您输入的人数过大',
'act_mobile_nickname_error'	=> '称呼和手机必填',
'act_num_overflow'			=> '总报名人数已超总人数',
'act_signup_nextstep'		=> '操作成功!\tnextto\tpw_ajax.php?action=activity&job=$GLOBALS[nextto]\ttid=$GLOBALS[tid]&thelast=1&actmid=$GLOBALS[actmid]&actuid=$GLOBALS[actuid]&totalsignupnums=$GLOBALS[totalsignupnums]&totalcash=$GLOBALS[totalcash]\t$GLOBALS[nextto]',
'act_confirmpay_error'		=> '只能确认未支付状态的报名信息',
'act_confirmpay_noright'	=> '您没有确认支付的权限',
'act_toalipay_payed'		=> "该订单已支付",
'act_toalipay_paymethod'	=> "操作错误，该支付方式不是支付宝",
'act_toalipay_cash_error'	=> "支付费用格式错误",
'act_toalipay_authorid'		=> '发起人无法帮TA人支付',
'act_toalipay_error'		=> '非法支付',
'act_export_noright'		=> '您没有导出权限',
'act_sendmsg_noright'		=> '您没有群发消息的权限',
'act_sendmsg_fail'			=> '还没有用户报名，不能群发消息',
'act_refund_error'			=> '该订单未支付或不是支付宝付款，无法退款',
'act_refund_cash_error'		=> '退款费用格式错误',
'act_isrefund_y'			=> '该订单已退款，请勿重复操作',
'act_refund_noright'		=> '您没有退款的权限',
'act_additional_noright'	=> '您没有追加费用的权限',
'act_model_undefined'		=> '该活动子分类未定义',
'act_model_disabled'		=> '该活动子分类未启用',
'act_cate_disabled'			=> '该活动分类未启用',
'act_iscancelled_y'			=> '该活动已取消',
'act_endtime_toolong'		=> '活动已经过期一个月，无法操作',
'act_iscancel_y_modify'		=> '此活动已取消，无法再编辑',
'act_close_payment_error'	=> '只能关闭未支付状态下的报名信息',
'act_close_payment_noright'	=> '您没有关闭报名信息的权限',
'act_refund_cost_finish'	=> '费用已全部退完，无法再退',
'act_signup_is_full'		=> '报名人数已满，无法报名',
'act_refund_nextstep'		=> '操作成功!\tnextto\tpw_ajax.php?action=activity&job=$GLOBALS[nextto]\ttid=$GLOBALS[tid]&thelast=1&actmid=$GLOBALS[actmid]&actuid=$GLOBALS[actuid]&cost=$GLOBALS[cost]\t$GLOBALS[nextto]',
'act_refund_costerror'		=> '退款费用错误',
'act_refund_reasonlenthlimit'=> '请输入您的退款原因或费用说明，最多128个字',
'act_alipay_sign_failure'	=> '签名验证失败',
'act_detailshow_error'		=> '您没有权限查看详情',
'act_modify_error'			=> '您没有权限修改报名信息',
'act_confirmpay_noright'	=> '您没有权限确认支付',
'act_refund_free'			=> '免费的活动不能退款',
'act_additional_free'		=> '免费的活动不能追加费用',
//圈子操作
'mode_o_no_activity'		=> '该活动不存在',
'mode_o_delactivity_permit_err'=> '您没有权限删除别人的活动',
//后台
'act_topic_name_error'		=> '分类名称不能为空或大小不能超过14字节',
'act_model_not_none'		=> '必须启用一个或一个以上分类',
'act_topic_edit_success'	=> "分类编辑成功\tjump\t{$GLOBALS[basename]}&",
'act_topic_del_success'		=> "分类删除成功\tjump\t{$GLOBALS[basename]}&",
'act_topic_undefined'		=> '该活动分类不存在',
'act_field_copy_success'	=> "字段复制完成\tjump\t{$GLOBALS[basename]}&action=editmodel&actid={$GLOBALS[actid]}&actmid={$GLOBALS[actmid]}",
'act_field_add_success'		=> "字段添加完成\tjump\t{$GLOBALS[basename]}&action=editmodel&actid={$GLOBALS[actid]}&actmid={$GLOBALS[actmid]}",
'act_field_edit_success'	=> "字段编辑完成\tjump\t{$GLOBALS[basename]}&action=editmodel&actid={$GLOBALS[actid]}&actmid={$GLOBALS[actmid]}",
'act_field_edit_forbidden'	=> '禁止编辑该字段',
'act_field_del_forbidden'	=> '禁止删除该字段',
'act_copyfield_none'		=> '请选择要导入的子分类字段',
'user_attention_exists'		=> "已关注",
'weibo_link_close'			=> '新鲜事发链接功能已关闭',
//拆分帖子
'split_no_thread'           => '没有要拆分的帖子',
'split_no_splitid'          => '帖子ID未填写',
'split_no_common_thread'    => '不能合并到当前主题',
'split_is_no_splitthread'   => '主题帖不存在',
'split_title_not_null'   => '新帖标题不得为空',
'split_title_not_big'   => '新帖标题小于100字符',
'split_no_thread' => '帖子不存在',
'split_not_all'  => '不能全部帖子拆分',
'stamp_have_exist'	=> '该名称的分类已存在，请重新修改名称',
'stamp_name_length'	=> '收藏分类的名称长度为1～20字节',   
);
?>