<?php
!defined('P_W') && exit('Forbidden');
return array(
	'value'		=> '个数',
	'postdate'	=> '时间',
	'url'		=> '链接地址',
	'image'		=> '图片地址',
	'descrip'	=> '描述',
	'costs'		=> '费用',
	'location'	=> '活动地点',
	'num'		=> '人数',
	'authorid'	=> '作者uid',
	'authorurl' => '作者url',
	'author'	=> '作者',
	'replies'	=> '回复数',
	'hits'		=> '点击数',
	'fid'		=> '版块fid',
	'forumname'	=> '版块名称',
	'forumurl'	=> '版块链接',
	'title_forum'=> '版块名称',
	'title_tag'	=> '标签名称',
	'title_user'=> '用户名',
	'title'		=> '标题',
	'length'	=> '长度：',
	'image_size'=> '图片长宽：',
	'html'		=> 'html代码',
	'titlealt'	=> '标题alt',
	'imgurl'	=> '图片链接',
	'business'	=> '商圈',
	'popularity'	=> '人气',
	'comments'	=> '点评',
	'icon'	=>'头像',
	'tags' =>'标签',
	'topictypename'	=>'主题分类',
	'topictypeurl'	=>'主题分类链接',
	'collectnum' =>'收藏数',
	'totalnum' => '总张数'
);
?>