<?php
!function_exists('readover') && exit('Forbidden');
$packClassFiles = array(
	'index' => array(
		'0' => 'lib/utility/cacheservice.class.php',
		'1' => 'lib/gather/gather.class.php',
		'2' => 'lib/user/db/membersdb.class.php',
		'3' => 'lib/user/db/singlerightdb.class.php',
		'4' => 'lib/site/navconfig.class.php',
		'5' => 'lib/forum/bbsinfoservice.class.php',
		'6' => 'lib/forum/db/bbsinfodb.class.php',
		'7' => 'lib/job/autojob.class.php',
		'8' => 'lib/job/db/joberdb.class.php',
		'9' => 'lib/framework/errors.class.php',
	),
	'thread' => array(
		'0' => 'lib/utility/cacheservice.class.php',
		'1' => 'lib/site/navconfig.class.php',
		'2' => 'lib/gather/gather.class.php',
		'3' => 'lib/forum/db/threadsdb.class.php',
		'4' => 'lib/job/autojob.class.php',
		'5' => 'lib/job/db/joberdb.class.php',
		'6' => 'lib/framework/errors.class.php',
		'7' => 'lib/gather/gathercache/pw_threads.cache.php',
	),
	'read' => array(
		'0' => 'lib/utility/cacheservice.class.php',
		'1' => 'lib/gather/gather.class.php',
		'2' => 'lib/forum/db/threadsdb.class.php',
		'3' => 'lib/site/navconfig.class.php',
		'4' => 'lib/forum/overprint.class.php',
		'5' => 'lib/utility/querybuilder.class.php',
		'6' => 'lib/user/db/membersdb.class.php',
		'7' => 'lib/user/db/membercreditdb.class.php',
		'8' => 'lib/forum/ping.class.php',
		'9' => 'lib/rate/rate.class.php',
		'10' => 'lib/rate/db/rateconfigdb.class.php',
		'11' => 'lib/rate/db/ratedb.class.php',
		'12' => 'lib/rate/db/rateresultdb.class.php',
		'13' => 'lib/job/autojob.class.php',
		'14' => 'lib/job/db/joberdb.class.php',
		'15' => 'lib/framework/errors.class.php',
		'16' => 'lib/user/userservice.class.php',
		'17' => 'lib/user/db/memberdatadb.class.php',
		'18' => 'lib/gather/gathercache/pw_threads.cache.php',
		'19' => 'lib/gather/gathercache/pw_members.cache.php',
	),
);

