<?php
!function_exists('readover') && exit('Forbidden');
$purview = array(
	'basic' => array('站点设置', "$admin_file?adminjob=settings&admintype=basic"),
	'customnav' => array('导航设置', "$admin_file?adminjob=customnav"),
	'safe' => array('安全优化', "$admin_file?adminjob=settings&admintype=safe"),
	'seoset' => array('SEO设置', "$admin_file?adminjob=seoset"),
	'att' => array('附件设置', "$admin_file?adminjob=settings&admintype=att"),
	'attachment' => array('附件优化', "$admin_file?adminjob=attachment"),
	'attachrenew' => array('附件修复', "$admin_file?adminjob=attachrenew"),
	'attachstats' => array('附件统计', "$admin_file?adminjob=attachstats"),
	'credit' => array('积分设置', "$admin_file?adminjob=settings&admintype=credit"),
	'reg' => array('注册控制', "$admin_file?adminjob=settings&admintype=reg"),
	'invite' => array('邀请注册', "$admin_file?adminjob=friend&admintype=invite"),
	'propagateset' => array('宣传控制', "$admin_file?adminjob=friend&admintype=propagateset"),

	'member' => array('会员相关', "$admin_file?adminjob=member"),
	'editer' => array('编辑器', "$admin_file?adminjob=editer"),
//	'pcache' => array('页面缓存', "$admin_file?adminjob=settings&admintype=pcache"),
	'bbssetting' => array('论坛设置', "$admin_file?adminjob=bbssetting"),
	//'index' => array('首页细节设置', "$admin_file?adminjob=settings&admintype=index"),
	//'thread' => array('帖子列表页设置', "$admin_file?adminjob=settings&admintype=thread"),
	//'read' => array('帖子阅读页设置', "$admin_file?adminjob=settings&admintype=read"),
	//'jsinvoke' => array('JS调用设置', "$admin_file?adminjob=settings&admintype=jsinvoke"),
	//'popinfo' => array('信息提示设置', "$admin_file?adminjob=settings&admintype=popinfo"),
	'email' => array('电子邮件', "$admin_file?adminjob=settings&admintype=email"),
	'wap' => array('WAP设置', "$admin_file?adminjob=settings&admintype=wap"),
	'urlcheck' => array('外链提醒', "$admin_file?adminjob=urlcheck"),
	'help' => array('帮助中心', "$admin_file?adminjob=help"),
	'sethtm' => array('伪静态', "$admin_file?adminjob=sethtm"),
	'setforum' => array('版块管理', "$admin_file?adminjob=setforum"),
	//'uniteforum' => array('版块合并', "$admin_file?adminjob=uniteforum"),
	//'creathtm' => array('生成静态文件', "$admin_file?adminjob=creathtm"),
	//'forumsell' => array('版块出售记录', "$admin_file?adminjob=forumsell"),
	'singleright' => array('版块权限', "$admin_file?adminjob=singleright"),
	'article' => array('帖子管理', "$admin_file?adminjob=thread&admintype=article"),
	'message' => array('消息管理', "$admin_file?adminjob=superdel&admintype=message"),
	'recycle' => array('回收站', "$admin_file?adminjob=recycle"),
	'draftset' => array('草稿箱', "$admin_file?adminjob=draftset"),
	'tpccheck' => array('帖子审核', "$admin_file?adminjob=tpccheck"),
	'report' => array('举报管理', "$admin_file?adminjob=report"),//注意后面的空格
	'reportcontent' => array('举报管理', "$admin_file?adminjob=report&adminitem=content"),
	'reportremind' => array('举报提醒', "$admin_file?adminjob=report&adminitem=remind"),
	'tagset' => array('标签管理', "$admin_file?adminjob=tagset"),
	//'pwcode' => array('自定义代码格式', "$admin_file?adminjob=pwcode"),
	//'setform' => array('预设帖子格式', "$admin_file?adminjob=setform"),
	'topiccate' => array('分类信息', "$admin_file?adminjob=topiccate"),
	'postcate' => array('团购', "$admin_file?adminjob=postcate"),
	'setbwd' => array('敏感词审核', "$admin_file?adminjob=setbwd"),
	//'postcache' => array('动作表情', "$admin_file?adminjob=postcache"),
	'activity' => array('活动',"$admin_file?adminjob=activity"),
	'usermanage' => array('用户管理', "$admin_file?adminjob=usermanage"),
	'level' => array('用户组权限', "$admin_file?adminjob=level"),
	'userstats' => array('成员统计', "$admin_file?adminjob=userstats"),
	'upgrade' => array('用户组提升', "$admin_file?adminjob=upgrade"),
	//'editgroup' => array('批量添加', "$admin_file?adminjob=editgroup"),
	'uptime' => array('有效期设置', "$admin_file?adminjob=uptime"),
	//'setuser' => array('会员管理', "$admin_file?adminjob=setuser"),
	//'unituser' => array('合并会员', "$admin_file?adminjob=unituser"),
	'banuser' => array('用户禁言', "$admin_file?adminjob=banuser"),
	'bansignature' => array('签名禁止', "$admin_file?adminjob=bansignature"),
	//'delmember' => array('删除会员', "$admin_file?adminjob=superdel&admintype=delmember"),
	'usercheck' => array('用户审核', "$admin_file?adminjob=usercheck"),
	//'customcredit' => array('自定义积分', "$admin_file?adminjob=customcredit"),
	'customfield' => array('扩展资料', "$admin_file?adminjob=customfield"),
	'bakup' => array('数据库',"$admin_file?adminjob=bakup"),
	'record' => array('管理日志',"$admin_file?adminjob=record"),
	'ipban' => array('IP 管理', "$admin_file?adminjob=ipban"),
	//'ipstates' => array('IP 统计', "$admin_file?adminjob=ipban&job=ipstates"),
	//'ipsearch' => array('IP 检索', "$admin_file?adminjob=ipban&job=ipsearch"),
	//'adminlog' => array('后台管理日志', "$admin_file?adminjob=record&admintype=adminlog"),
	//'forumlog' => array('前台管理日志', "$admin_file?adminjob=forumlog"),
	'creditlog' => array('积分统计', "$admin_file?adminjob=creditlog"),
	'tucool'=>array('图酷数据',"$admin_file?adminjob=tucool"),
	//'adminrecord' => array('后台操作记录', "$admin_file?adminjob=adminrecord"),
	/*'bakup' => array('数据维护', "$admin_file?adminjob=bakup"), 
	'ptable' => array('数据库分卷', "$admin_file?adminjob=ptable"),*/
	'aboutcache' => array('全站缓存', "$admin_file?adminjob=aboutcache"),
	//'updatecache' => array('缓存管理', "$admin_file?adminjob=updatecache"),
	//'pwcache' => array('PW缓存库', "$admin_file?adminjob=pwcache"),
	//'guestdir' => array('缓存文件清理', "$admin_file?adminjob=guestdir"),
	'filecheck' => array('文件检查', "$admin_file?adminjob=filecheck"),
	//'safecheck' => array('文件安全检查', "$admin_file?adminjob=safecheck"),
	'datastate' => array('数据统计', "$admin_file?adminjob=datastate"),
	'viewtoday' => array('今日会员', "$admin_file?adminjob=viewtoday"),
	'hackcenter' => array('插件中心', "$admin_file?adminjob=hackcenter"),
	'setstyles' => array('风格模板', "$admin_file?adminjob=setstyles"),
	'userpay' => array('网上支付', "$admin_file?adminjob=userpay&adminitem=userpay"),
	//'orderlist' => array('订单管理', "$admin_file?adminjob=orderlist"),
	'announcement' => array('公告管理', "$admin_file?adminjob=announcement"),
	'sendmail' => array('邮件群发', "$admin_file?adminjob=sendmail"),
	'sendmsg' => array('消息群发', "$admin_file?adminjob=sendmsg"),
	'present' => array('节日送礼', "$admin_file?adminjob=present"), //	'setads'		=> array('宣传设置',"$admin_file?adminjob=setads"),
	'share' => array('友情链接', "$admin_file?adminjob=share"),
	//'sitemap' => array('网站地图', "$admin_file?adminjob=sitemap"),
	'interfacesettings' => array('界面设置',"$admin_file?adminjob=interfacesettings"),
	'rebang' => array('内容推送', "$admin_file?adminjob=rebang"),
	'plantodo' => array('计划任务', "$admin_file?adminjob=plantodo"),
	'team' => array('团队考核', "$admin_file?adminjob=team"),
	'modeset' => array('模式设置', "$admin_file?adminjob=modeset"),
	//'area_pushdata'	=> array('内容推送',"$admin_file?adminjob=mode&admintype=area_pushdata"),
	//'cms_article' => array('内容管理',"$admin_file?adminjob=mode&admintype=cms_article"),	
	/*'area_channel_manage'	=> array('频道管理',"$admin_file?adminjob=mode&admintype=area_channel_manage"),
	'area_pushdata'	=> array('内容推送管理',"$admin_file?adminjob=mode&admintype=area_pushdata"),
	'area_level_manage' => array('权限管理',"$admin_file?adminjob=mode&admintype=area_level_manage"),
	'area_selecttpl'	=> array('模板中心',"$admin_file?adminjob=mode&admintype=area_selecttpl"),
	'area_static_manage'	=> array('静态配置',"$admin_file?adminjob=mode&admintype=area_static_manage"),
	//'area_edittpl'	=> array('本站模板管理',"$admin_file?adminjob=mode&admintype=area_edittpl"),
	//'area_tplcontent'	=> array('模块内容管理',"$admin_file?adminjob=mode&admintype=area_tplcontent"),
	//'area_configarea'	=> array('门户页面静态化',"$admin_file?adminjob=mode&admintype=area_configarea"),
	'area_module'	=> array('模块管理',"$admin_file?adminjob=mode&admintype=area_module"),
	*/
	'o_tags' => array('个人标签管理', "$admin_file?adminjob=mode&admintype=o_tags"),
	'o_global' => array('个人中心设置', "$admin_file?adminjob=mode&admintype=o_global"),
	'o_commend' => array('内容推送',"$admin_file?adminjob=mode&admintype=o_commend"),
	'o_skin' => array('风格设置', "$admin_file?adminjob=mode&admintype=o_skin"),
	'rightset' => array('权限管理', "$admin_file?adminjob=rightset"),
	'manager' => array('创始人管理', "$admin_file?adminjob=manager"),
	'ystats' => array('量子统计', "$admin_file?adminjob=ystats&action=config"),
	'diyoption' => array('常用定制', "$admin_file?adminjob=diyoption"),
	//'msphinx' => array('Sphinx全文索引', "$admin_file?adminjob=advanced&admintype=msphinx"),
	//'mmemcache' => array('Memcache缓存', "$admin_file?adminjob=advanced&admintype=mmemcache"),
	'advanced' => array('高级应用配置', "$admin_file?adminjob=advanced"),
	'optimize' => array('站点优化', "$admin_file?adminjob=optimize"),
	//'maketemplate' => array('模块生成', "$admin_file?adminjob=maketemplate"),
	//'all'			=> array('所有选项',"$admin_file?adminjob=settings&admintype=all"),
	/*'navmain' => array('社区主导航', "$admin_file?adminjob=customnav&admintype=navmain"),
	'navside' => array('顶部底部导航', "$admin_file?adminjob=customnav&admintype=navside"),*/
	//'navmode'		=> array('模式导航',"$admin_file?adminjob=customnav&admintype=navmode"),
	'setadvert' => array('广告管理', "$admin_file?adminjob=setadvert"),
	'postindex' => array('帖子索引', "$admin_file?adminjob=postindex"),
	'ucset' => array('用户中心设置', "$admin_file?adminjob=ucset"), 'ucapp' => array('应用管理', "$admin_file?adminjob=ucapp"),
	'uccredit' => array('积分同步', "$admin_file?adminjob=uccredit"),
	'ucnotify' => array('消息队列', "$admin_file?adminjob=ucnotify"),
	'o_comments' => array('评论管理', "$admin_file?adminjob=mode&admintype=o_comments"),
	'taolianjie' => array('淘链接',"$admin_file?adminjob=app&admintype=taolianjie"),
	'sinaweibo' => array('新浪微博',"$admin_file?adminjob=app&admintype=sinaweibo"),
	'authentication' => array('实名认证',"$admin_file?adminjob=authentication"),
	'yunstatistics' => array('云统计<i class="beta">&nbsp;</i>',"$admin_file?adminjob=app&admintype=yunstatistics"),
	//'appslist' => array('基本设置', "$admin_file?adminjob=app&admintype=appslist"),
	'appset' => array('应用首页', "$admin_file?adminjob=app&admintype=appset"),
	'onlineapp' => array('会员应用', "$admin_file?adminjob=app&admintype=onlineapp"),
	'i9p' => array('随拍随发', "$admin_file?adminjob=app&admintype=i9p"),
	'blooming' => array('帖子交换', "$admin_file?adminjob=app&admintype=blooming"),
	'job' => array('任务中心', "$admin_file?adminjob=job"),
	//'overprint' => array('主题印戳', "$admin_file?adminjob=overprint"),
	//'app' => array('APP平台帐号', "$admin_file?adminjob=app"),
	'messageset' => array('消息设置', "$admin_file?adminjob=messageset"),
	'searcher' => array('搜索设置', "$admin_file?adminjob=searcher"),

	'photos_set' => array('相册', "$admin_file?adminjob=apps&admintype=photos_set"),
	'photos_manage' => array('相册管理', "$admin_file?adminjob=apps&admintype=photos_manage"),
	'diary_set' => array('日志', "$admin_file?adminjob=apps&admintype=diary_set"),
	'diary_manage' => array('日志管理', "$admin_file?adminjob=apps&admintype=diary_manage"),
	'groups_set' => array('群组', "$admin_file?adminjob=apps&admintype=groups_set"),
	'groups_manage' => array('群组管理', "$admin_file?adminjob=apps&admintype=groups_manage"),
	//'app_share' => array('分享管理', "$admin_file?adminjob=apps&admintype=app_share&action=share"),
	'weibo_set' => array('新鲜事', "$admin_file?adminjob=apps&admintype=weibo_set"),
	'weibo_manage' => array('新鲜事管理', "$admin_file?adminjob=apps&admintype=weibo_manage"),

	'hot' => array('热榜', "$admin_file?adminjob=apps&admintype=hot"),
	'stopic' => array('专题制作', "$admin_file?adminjob=apps&admintype=stopic"),
);

//模式菜单加载
extract(pwCache::getData( D_P . 'data/bbscache/config.php' , false));
if ($db_modes) {
	foreach ($db_modes as $key => $value) {
		if ($value['ifopen'] && file_exists(R_P . 'mode/' . $key . '/config/cp_lang_purview.php')) {
			include R_P . 'mode/' . $key . '/config/cp_lang_purview.php';
		}
	}
}

/*动态加载扩展菜单*/
$extentPath = R_P.'require/extents/menu';
if ($fp = opendir($extentPath)) {
	while (($filename = readdir($fp))) {
		if($filename=='..' || $filename=='.') continue;
		$leftFile = $extentPath.'/'.$filename.'/cp_lang_purview.php';
		if (file_exists($leftFile)) include $leftFile;
	}
}

?>